export interface Weapon {
  name: string
  category: "Simple Melee" | "Simple Ranged" | "Martial Melee" | "Martial Ranged"
  damage: string
  damageType: string
  properties: string[]
  weight: string
  cost: string
}

export interface Armor {
  name: string
  category: "Light" | "Medium" | "Heavy" | "Shield"
  ac: string
  stealthDisadvantage: boolean
  strengthRequirement?: number
  weight: string
  cost: string
}

export const WEAPONS: Weapon[] = [
  // Simple Melee
  {
    name: "Club",
    category: "Simple Melee",
    damage: "1d4",
    damageType: "Bludgeoning",
    properties: ["Light"],
    weight: "2 lb.",
    cost: "1 sp",
  },
  {
    name: "Dagger",
    category: "Simple Melee",
    damage: "1d4",
    damageType: "Piercing",
    properties: ["Finesse", "Light", "Thrown (20/60)"],
    weight: "1 lb.",
    cost: "2 gp",
  },
  {
    name: "Greatclub",
    category: "Simple Melee",
    damage: "1d8",
    damageType: "Bludgeoning",
    properties: ["Two-Handed"],
    weight: "10 lb.",
    cost: "2 sp",
  },
  {
    name: "Handaxe",
    category: "Simple Melee",
    damage: "1d6",
    damageType: "Slashing",
    properties: ["Light", "Thrown (20/60)"],
    weight: "2 lb.",
    cost: "5 gp",
  },
  {
    name: "Javelin",
    category: "Simple Melee",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Thrown (30/120)"],
    weight: "2 lb.",
    cost: "5 sp",
  },
  {
    name: "Light Hammer",
    category: "Simple Melee",
    damage: "1d4",
    damageType: "Bludgeoning",
    properties: ["Light", "Thrown (20/60)"],
    weight: "2 lb.",
    cost: "2 gp",
  },
  {
    name: "Mace",
    category: "Simple Melee",
    damage: "1d6",
    damageType: "Bludgeoning",
    properties: [],
    weight: "4 lb.",
    cost: "5 gp",
  },
  {
    name: "Quarterstaff",
    category: "Simple Melee",
    damage: "1d6",
    damageType: "Bludgeoning",
    properties: ["Versatile (1d8)"],
    weight: "4 lb.",
    cost: "2 sp",
  },
  {
    name: "Sickle",
    category: "Simple Melee",
    damage: "1d4",
    damageType: "Slashing",
    properties: ["Light"],
    weight: "2 lb.",
    cost: "1 gp",
  },
  {
    name: "Spear",
    category: "Simple Melee",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Thrown (20/60)", "Versatile (1d8)"],
    weight: "3 lb.",
    cost: "1 gp",
  },

  // Simple Ranged
  {
    name: "Light Crossbow",
    category: "Simple Ranged",
    damage: "1d8",
    damageType: "Piercing",
    properties: ["Ammunition (80/320)", "Loading", "Two-Handed"],
    weight: "5 lb.",
    cost: "25 gp",
  },
  {
    name: "Dart",
    category: "Simple Ranged",
    damage: "1d4",
    damageType: "Piercing",
    properties: ["Finesse", "Thrown (20/60)"],
    weight: "1/4 lb.",
    cost: "5 cp",
  },
  {
    name: "Shortbow",
    category: "Simple Ranged",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Ammunition (80/320)", "Two-Handed"],
    weight: "2 lb.",
    cost: "25 gp",
  },
  {
    name: "Sling",
    category: "Simple Ranged",
    damage: "1d4",
    damageType: "Bludgeoning",
    properties: ["Ammunition (30/120)"],
    weight: "—",
    cost: "1 sp",
  },

  // Martial Melee
  {
    name: "Battleaxe",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Slashing",
    properties: ["Versatile (1d10)"],
    weight: "4 lb.",
    cost: "10 gp",
  },
  {
    name: "Flail",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Bludgeoning",
    properties: [],
    weight: "2 lb.",
    cost: "10 gp",
  },
  {
    name: "Glaive",
    category: "Martial Melee",
    damage: "1d10",
    damageType: "Slashing",
    properties: ["Heavy", "Reach", "Two-Handed"],
    weight: "6 lb.",
    cost: "20 gp",
  },
  {
    name: "Greataxe",
    category: "Martial Melee",
    damage: "1d12",
    damageType: "Slashing",
    properties: ["Heavy", "Two-Handed"],
    weight: "7 lb.",
    cost: "30 gp",
  },
  {
    name: "Greatsword",
    category: "Martial Melee",
    damage: "2d6",
    damageType: "Slashing",
    properties: ["Heavy", "Two-Handed"],
    weight: "6 lb.",
    cost: "50 gp",
  },
  {
    name: "Halberd",
    category: "Martial Melee",
    damage: "1d10",
    damageType: "Slashing",
    properties: ["Heavy", "Reach", "Two-Handed"],
    weight: "6 lb.",
    cost: "20 gp",
  },
  {
    name: "Lance",
    category: "Martial Melee",
    damage: "1d12",
    damageType: "Piercing",
    properties: ["Reach", "Special"],
    weight: "6 lb.",
    cost: "10 gp",
  },
  {
    name: "Longsword",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Slashing",
    properties: ["Versatile (1d10)"],
    weight: "3 lb.",
    cost: "15 gp",
  },
  {
    name: "Maul",
    category: "Martial Melee",
    damage: "2d6",
    damageType: "Bludgeoning",
    properties: ["Heavy", "Two-Handed"],
    weight: "10 lb.",
    cost: "10 gp",
  },
  {
    name: "Morningstar",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Piercing",
    properties: [],
    weight: "4 lb.",
    cost: "15 gp",
  },
  {
    name: "Pike",
    category: "Martial Melee",
    damage: "1d10",
    damageType: "Piercing",
    properties: ["Heavy", "Reach", "Two-Handed"],
    weight: "18 lb.",
    cost: "5 gp",
  },
  {
    name: "Rapier",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Piercing",
    properties: ["Finesse"],
    weight: "2 lb.",
    cost: "25 gp",
  },
  {
    name: "Scimitar",
    category: "Martial Melee",
    damage: "1d6",
    damageType: "Slashing",
    properties: ["Finesse", "Light"],
    weight: "3 lb.",
    cost: "25 gp",
  },
  {
    name: "Shortsword",
    category: "Martial Melee",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Finesse", "Light"],
    weight: "2 lb.",
    cost: "10 gp",
  },
  {
    name: "Trident",
    category: "Martial Melee",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Thrown (20/60)", "Versatile (1d8)"],
    weight: "4 lb.",
    cost: "5 gp",
  },
  {
    name: "War Pick",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Piercing",
    properties: [],
    weight: "2 lb.",
    cost: "5 gp",
  },
  {
    name: "Warhammer",
    category: "Martial Melee",
    damage: "1d8",
    damageType: "Bludgeoning",
    properties: ["Versatile (1d10)"],
    weight: "2 lb.",
    cost: "15 gp",
  },
  {
    name: "Whip",
    category: "Martial Melee",
    damage: "1d4",
    damageType: "Slashing",
    properties: ["Finesse", "Reach"],
    weight: "3 lb.",
    cost: "2 gp",
  },

  // Martial Ranged
  {
    name: "Blowgun",
    category: "Martial Ranged",
    damage: "1",
    damageType: "Piercing",
    properties: ["Ammunition (25/100)", "Loading"],
    weight: "1 lb.",
    cost: "10 gp",
  },
  {
    name: "Hand Crossbow",
    category: "Martial Ranged",
    damage: "1d6",
    damageType: "Piercing",
    properties: ["Ammunition (30/120)", "Light", "Loading"],
    weight: "3 lb.",
    cost: "75 gp",
  },
  {
    name: "Heavy Crossbow",
    category: "Martial Ranged",
    damage: "1d10",
    damageType: "Piercing",
    properties: ["Ammunition (100/400)", "Heavy", "Loading", "Two-Handed"],
    weight: "18 lb.",
    cost: "50 gp",
  },
  {
    name: "Longbow",
    category: "Martial Ranged",
    damage: "1d8",
    damageType: "Piercing",
    properties: ["Ammunition (150/600)", "Heavy", "Two-Handed"],
    weight: "2 lb.",
    cost: "50 gp",
  },
  {
    name: "Net",
    category: "Martial Ranged",
    damage: "—",
    damageType: "—",
    properties: ["Special", "Thrown (5/15)"],
    weight: "3 lb.",
    cost: "1 gp",
  },
]

export const ARMOR: Armor[] = [
  // Light Armor
  {
    name: "Padded",
    category: "Light",
    ac: "11 + Dex modifier",
    stealthDisadvantage: true,
    weight: "8 lb.",
    cost: "5 gp",
  },
  {
    name: "Leather",
    category: "Light",
    ac: "11 + Dex modifier",
    stealthDisadvantage: false,
    weight: "10 lb.",
    cost: "10 gp",
  },
  {
    name: "Studded Leather",
    category: "Light",
    ac: "12 + Dex modifier",
    stealthDisadvantage: false,
    weight: "13 lb.",
    cost: "45 gp",
  },

  // Medium Armor
  {
    name: "Hide",
    category: "Medium",
    ac: "12 + Dex modifier (max 2)",
    stealthDisadvantage: false,
    weight: "12 lb.",
    cost: "10 gp",
  },
  {
    name: "Chain Shirt",
    category: "Medium",
    ac: "13 + Dex modifier (max 2)",
    stealthDisadvantage: false,
    weight: "20 lb.",
    cost: "50 gp",
  },
  {
    name: "Scale Mail",
    category: "Medium",
    ac: "14 + Dex modifier (max 2)",
    stealthDisadvantage: true,
    weight: "45 lb.",
    cost: "50 gp",
  },
  {
    name: "Breastplate",
    category: "Medium",
    ac: "14 + Dex modifier (max 2)",
    stealthDisadvantage: false,
    weight: "20 lb.",
    cost: "400 gp",
  },
  {
    name: "Half Plate",
    category: "Medium",
    ac: "15 + Dex modifier (max 2)",
    stealthDisadvantage: true,
    weight: "40 lb.",
    cost: "750 gp",
  },

  // Heavy Armor
  { name: "Ring Mail", category: "Heavy", ac: "14", stealthDisadvantage: true, weight: "40 lb.", cost: "30 gp" },
  {
    name: "Chain Mail",
    category: "Heavy",
    ac: "16",
    stealthDisadvantage: true,
    strengthRequirement: 13,
    weight: "55 lb.",
    cost: "75 gp",
  },
  {
    name: "Splint",
    category: "Heavy",
    ac: "17",
    stealthDisadvantage: true,
    strengthRequirement: 15,
    weight: "60 lb.",
    cost: "200 gp",
  },
  {
    name: "Plate",
    category: "Heavy",
    ac: "18",
    stealthDisadvantage: true,
    strengthRequirement: 15,
    weight: "65 lb.",
    cost: "1,500 gp",
  },

  // Shield
  { name: "Shield", category: "Shield", ac: "+2", stealthDisadvantage: false, weight: "6 lb.", cost: "10 gp" },
]
