export interface Spell {
  name: string
  level: number // 0 = cantrip
  school: string
  classes: string[]
  castingTime: string
  range: string
  components: string
  duration: string
  description: string
  higherLevel?: string
}

export const SPELL_SCHOOLS = [
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "Illusion",
  "Necromancy",
  "Transmutation",
] as const

export const SPELLS: Spell[] = [
  // Cantrips
  {
    name: "Acid Splash",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You create an acidic bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere must succeed on a Dexterity saving throw or take 1d6 Acid damage.",
    higherLevel: "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
  },
  {
    name: "Blade Ward",
    level: 0,
    school: "Abjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description:
      "Whenever a creature makes an attack roll against you before the spell ends, the attacker subtracts 1d4 from the attack roll.",
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "Necromancy",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Make a melee spell attack against a creature you can reach. On a hit, the target takes 1d10 Necrotic damage, and it can't regain Hit Points until the end of your next turn.",
    higherLevel: "The damage increases by 1d10 when you reach levels 5 (2d10), 11 (3d10), and 17 (4d10).",
  },
  {
    name: "Dancing Lights",
    level: 0,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a bit of phosphorus)",
    duration: "Concentration, up to 1 minute",
    description:
      "You create up to four torch-sized lights within range, making them appear as torches, lanterns, or glowing orbs that hover for the duration. You can combine the lights into one glowing humanoid form of Medium size. On each of your turns, you can move the lights up to 60 feet to a new spot within range as a Bonus Action.",
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    classes: ["Warlock"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You hurl a beam of crackling energy. Make a ranged spell attack against one creature within range. On a hit, the target takes 1d10 Force damage.",
    higherLevel:
      "The spell creates more than one beam when you reach higher levels: two beams at level 5, three beams at level 11, and four beams at level 17. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.",
  },
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You hurl a mote of fire at a creature or an object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 Fire damage. A flammable object hit by this spell catches fire if it isn't being worn or carried.",
    higherLevel: "The damage increases by 1d10 when you reach levels 5 (2d10), 11 (3d10), and 17 (4d10).",
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    classes: ["Cleric", "Druid"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description:
      "You touch a willing creature and choose a skill. Until the spell ends, the creature adds 1d4 to any ability check using the chosen skill.",
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, M (a firefly or phosphorescent moss)",
    duration: "1 hour",
    description:
      "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. The light can be colored as you like.",
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "1 minute",
    description:
      "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial.",
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "S, M (a bit of fleece)",
    duration: "1 minute",
    description:
      "You create a sound or an image of an object within range that lasts for the duration. If you create a sound, its volume can range from a whisper to a scream. If you create an image of an object, it must be no larger than a 5-foot Cube.",
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "10 feet",
    components: "V, S",
    duration: "Up to 1 hour",
    description:
      "You create a minor magical effect within range. You can create sensory effects, light or snuff a small flame, clean or soil an object, chill/warm/flavor material, make a symbol appear, or create a trinket or illusory image.",
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 Cold damage, and its Speed is reduced by 10 feet until the start of your next turn.",
    higherLevel: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 Radiant damage. The target gains no benefit from Half Cover or Three-Quarters Cover for this save.",
    higherLevel: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Lightning springs from you to a creature that you try to touch. Make a melee spell attack against the target, with Advantage if it's wearing Armor made of metal. On a hit, the target takes 1d8 Lightning damage, and it can't take Reactions until the start of its next turn.",
    higherLevel: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "30 feet",
    components: "V",
    duration: "Up to 1 minute",
    description:
      "You manifest a minor wonder within range: your voice booms, flames flicker/change color, tremors run through the ground, create sounds, cause doors/windows to fly open/shut, or alter your eye appearance.",
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    classes: ["Bard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "You unleash a string of insults laced with subtle enchantments at one creature you can see within range. The target must succeed on a Wisdom saving throw or take 1d6 Psychic damage and have Disadvantage on the next attack roll it makes before the end of its next turn.",
    higherLevel: "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
  },

  // Level 1 Spells
  {
    name: "Alarm",
    level: 1,
    school: "Abjuration",
    classes: ["Ranger", "Wizard"],
    castingTime: "1 minute or Ritual",
    range: "30 feet",
    components: "V, S, M (a bell and silver wire)",
    duration: "8 hours",
    description:
      "You set an alarm against intrusion. Choose a door, window, or area within range no larger than a 20-foot Cube. Until the spell ends, an alarm alerts you whenever a creature touches or enters the warded area. You can designate creatures that won't set off the alarm and choose audible or mental alarm.",
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    classes: ["Cleric", "Paladin"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a drop of holy water)",
    duration: "Concentration, up to 1 minute",
    description:
      "You bless up to three creatures within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target adds 1d4 to the roll.",
    higherLevel: "You can target one additional creature for each spell slot level above 1.",
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (15-foot cone)",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot Cone makes a Dexterity saving throw, taking 3d6 Fire damage on a failed save or half as much on a successful one. The fire ignites flammable objects in the area.",
    higherLevel: "The damage increases by 1d6 for each spell slot level above 1.",
  },
  {
    name: "Charm Person",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "1 hour",
    description:
      "You attempt to charm a Humanoid you can see within range. It makes a Wisdom saving throw with Advantage if you or your companions are fighting it. On a failed save, the target is Charmed by you until the spell ends or until you or your companions do anything harmful to it.",
    higherLevel: "You can target one additional creature for each spell slot level above 1.",
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A creature you touch regains a number of Hit Points equal to 2d8 plus your spellcasting ability modifier. This spell has no effect on Constructs or Undead.",
    higherLevel: "The healing increases by 2d8 for each spell slot level above 1.",
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Action or Ritual",
    range: "Self (30-foot radius)",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description:
      "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can take a Magic action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.",
  },
  {
    name: "Disguise Self",
    level: 1,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "1 hour",
    description:
      "You make yourself—including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends. You can seem 1 foot shorter or taller and can appear thin, fat, or in between. You can't change your body type, so you must adopt a form that has the same basic arrangement of limbs.",
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Concentration, up to 1 minute",
    description:
      "Objects in a 20-foot Cube within range are outlined in blue, green, or violet light (your choice). Each creature in the area makes a Dexterity saving throw. On a failed save, the creature is outlined for the duration. Attack rolls against an outlined creature have Advantage, and the creature can't benefit from the Invisible condition.",
  },
  {
    name: "Feather Fall",
    level: 1,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Reaction",
    range: "60 feet",
    components: "V, M (a small feather)",
    duration: "1 minute",
    description:
      "Reaction trigger: You or a creature within 60 feet of you falls. Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage, and the spell ends for that creature.",
  },
  {
    name: "Fog Cloud",
    level: 1,
    school: "Conjuration",
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Concentration, up to 1 hour",
    description:
      "You create a 20-foot-radius Sphere of fog centered on a point within range. The Sphere is Heavily Obscured. It lasts for the duration or until a strong wind (at least 20 miles per hour) disperses it.",
    higherLevel: "The fog's radius increases by 20 feet for each spell slot level above 1.",
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "Bonus Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "A creature of your choice that you can see within range regains Hit Points equal to 2d4 plus your spellcasting ability modifier. This spell has no effect on Constructs or Undead.",
    higherLevel: "The healing increases by 2d4 for each spell slot level above 1.",
  },
  {
    name: "Identify",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Wizard"],
    castingTime: "1 minute or Ritual",
    range: "Touch",
    components: "V, S, M (a pearl worth 100+ GP)",
    duration: "Instantaneous",
    description:
      "You choose one object that you must touch throughout the casting. If it's a magic item or some other magic-imbued object, you learn its properties and how to use them. You also learn whether any spells are affecting the item and what they are.",
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "Abjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a piece of cured leather)",
    duration: "8 hours",
    description:
      "You touch a willing creature who isn't wearing armor. Until the spell ends, the target's base AC becomes 13 + its Dexterity modifier. The spell ends early if the target dons armor or if you dismiss the spell.",
  },
  {
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 Force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
    higherLevel: "You create one additional dart for each spell slot level above 1.",
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Reaction",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    description:
      "Reaction trigger: You're hit by an attack roll or targeted by Magic Missile. An invisible barrier of magical force protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile.",
  },
  {
    name: "Sleep",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a pinch of sand)",
    duration: "Concentration, up to 1 minute",
    description:
      "Each creature of your choice in a 5-foot-radius Sphere centered on a point within range must succeed on a Wisdom saving throw or have the Unconscious condition until the spell ends. A Sleeper wakes up if it takes damage or if someone uses an action to shake it awake.",
    higherLevel: "The Sphere's radius increases by 5 feet for each spell slot level above 1.",
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (15-foot cube)",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A wave of thunderous force sweeps out from you. Each creature in a 15-foot Cube originating from you makes a Constitution saving throw. On a failed save, a creature takes 2d8 Thunder damage and is pushed 10 feet away from you. On a successful save, it takes half damage only.",
    higherLevel: "The damage increases by 1d8 for each spell slot level above 1.",
  },

  // Level 2 Spells
  {
    name: "Acid Arrow",
    level: 2,
    school: "Evocation",
    classes: ["Wizard"],
    castingTime: "Action",
    range: "90 feet",
    components: "V, S, M (powdered rhubarb leaf)",
    duration: "Instantaneous",
    description:
      "A shimmering green arrow streaks toward a target within range and bursts in a spray of acid. Make a ranged spell attack against the target. On a hit, the target takes 4d4 Acid damage and 2d4 Acid damage at the end of its next turn. On a miss, the arrow splashes the target for half initial damage only.",
    higherLevel: "The damage (both initial and later) increases by 1d4 for each spell slot level above 2.",
  },
  {
    name: "Aid",
    level: 2,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a strip of white cloth)",
    duration: "8 hours",
    description:
      "Choose up to three creatures within range. Each target's Hit Point maximum and current Hit Points increase by 5 for the duration.",
    higherLevel: "Each target's Hit Points increase by 5 for each spell slot level above 2.",
  },
  {
    name: "Darkness",
    level: 2,
    school: "Evocation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, M (bat fur and a piece of coal)",
    duration: "Concentration, up to 10 minutes",
    description:
      "Magical darkness spreads from a point within range to fill a 15-foot-radius Sphere for the duration. Darkvision can't see through this darkness. Nonmagical light can't illuminate it. Covering the source of the darkness with something opaque blocks the darkness.",
  },
  {
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a straight piece of iron)",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a Humanoid that you can see within range. The target must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success.",
    higherLevel: "You can target one additional Humanoid for each spell slot level above 2.",
  },
  {
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (an eyelash in gum arabic)",
    duration: "Concentration, up to 1 hour",
    description:
      "A creature you touch has the Invisible condition until the spell ends. The spell ends early immediately after the target makes an attack roll, deals damage, or casts a spell.",
    higherLevel: "You can target one additional creature for each spell slot level above 2.",
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Bonus Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You touch a creature and end one condition on it: Blinded, Deafened, Paralyzed, or Poisoned. Alternatively, you can end one disease or other effect caused by poison or disease.",
  },
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Bonus Action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.",
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 Fire damage.",
    higherLevel: "You create one additional ray for each spell slot level above 2.",
  },
  {
    name: "Shatter",
    level: 2,
    school: "Evocation",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a chip of mica)",
    duration: "Instantaneous",
    description:
      "A loud noise erupts from a point of your choice within range. Each creature in a 10-foot-radius Sphere centered on that point makes a Constitution saving throw, taking 3d8 Thunder damage on a failed save or half as much on a successful one. A creature made of inorganic material has Disadvantage on the save.",
    higherLevel: "The damage increases by 1d8 for each spell slot level above 2.",
  },
  {
    name: "Suggestion",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, M (a snake's tongue)",
    duration: "Concentration, up to 8 hours",
    description:
      "You suggest a course of activity (limited to a sentence or two) and magically influence a creature you can see within range that can hear and understand you. Creatures that can't be Charmed are immune. The suggestion must sound reasonable. The target must succeed on a Wisdom saving throw or pursue the course of action you described.",
  },
  {
    name: "Web",
    level: 2,
    school: "Conjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a bit of spiderweb)",
    duration: "Concentration, up to 1 hour",
    description:
      "You conjure a mass of thick, sticky webbing at a point of your choice within range. The webs fill a 20-foot Cube for the duration. The webs are Difficult Terrain and Lightly Obscure their area. A creature that starts its turn in the webs or enters them during its turn must succeed on a Dexterity saving throw or have the Restrained condition while in the webs or until it breaks free.",
  },

  // Level 3 Spells
  {
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Reaction",
    range: "60 feet",
    components: "S",
    duration: "Instantaneous",
    description:
      "Reaction trigger: A creature within 60 feet of you is casting a spell. You attempt to interrupt the spell. If it's a level 3 spell or lower, the spell fails and has no effect. If it's level 4 or higher, make an ability check using your spellcasting ability (DC = 10 + spell's level). On a success, the spell fails.",
    higherLevel:
      "The interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.",
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Choose one creature, object, or magical effect within range. Any spell of level 3 or lower on the target ends. For each spell of level 4 or higher, make an ability check using your spellcasting ability (DC = 10 + the spell's level). On a successful check, the spell ends.",
    higherLevel:
      "You automatically end the effects of a spell on the target if the spell's level is equal to or less than the level of the spell slot you used.",
  },
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "150 feet",
    components: "V, S, M (a ball of bat guano and sulfur)",
    duration: "Instantaneous",
    description:
      "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius Sphere centered on that point makes a Dexterity saving throw, taking 8d6 Fire damage on a failed save or half as much on a successful one.",
    higherLevel: "The damage increases by 1d6 for each spell slot level above 3.",
  },
  {
    name: "Fly",
    level: 3,
    school: "Transmutation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a feather)",
    duration: "Concentration, up to 10 minutes",
    description:
      "You touch a willing creature. The target gains a Fly Speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft.",
    higherLevel: "You can target one additional creature for each spell slot level above 3.",
  },
  {
    name: "Haste",
    level: 3,
    school: "Transmutation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a shaving of licorice root)",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a willing creature that you can see within range. Until the spell ends, the target's Speed is doubled, it gains a +2 bonus to AC, it has Advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action. When the spell ends, the target can't move or take actions until after its next turn.",
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (100-foot line)",
    components: "V, S, M (fur and a crystal rod)",
    duration: "Instantaneous",
    description:
      "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line makes a Dexterity saving throw, taking 8d6 Lightning damage on a failed save or half as much on a successful one.",
    higherLevel: "The damage increases by 1d6 for each spell slot level above 3.",
  },
  {
    name: "Revivify",
    level: 3,
    school: "Necromancy",
    classes: ["Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a diamond worth 300+ GP, which the spell consumes)",
    duration: "Instantaneous",
    description:
      "You touch a creature that has died within the last minute. That creature revives with 1 Hit Point. This spell can't revive a creature that has died of old age, nor can it restore any missing body parts.",
  },

  // Level 4 Spells
  {
    name: "Banishment",
    level: 4,
    school: "Abjuration",
    classes: ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a pinch of salt)",
    duration: "Concentration, up to 1 minute",
    description:
      "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be transported. If the target is native to a different plane than the one you're on, the target is banished with a faint popping noise, returning to its home plane. If the target is native to the plane you're on, the target is banished to a harmless demiplane.",
    higherLevel: "You can target one additional creature for each spell slot level above 4.",
  },
  {
    name: "Dimension Door",
    level: 4,
    school: "Conjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "500 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. You can also bring one willing creature of your size or smaller who is within 5 feet of you.",
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description:
      "You or a creature you touch has the Invisible condition until the spell ends. Unlike regular Invisibility, the effect doesn't end early if the target makes an attack, deals damage, or casts a spell.",
  },
  {
    name: "Polymorph",
    level: 4,
    school: "Transmutation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a caterpillar cocoon)",
    duration: "Concentration, up to 1 hour",
    description:
      "You attempt to transform a creature that you can see within range into a Beast. The target must succeed on a Wisdom saving throw or shape-shift into Beast form for the duration. An unwilling target can repeat the save at the end of each of its turns. The transformation lasts until the target drops to 0 HP or the spell ends.",
  },
  {
    name: "Wall of Fire",
    level: 4,
    school: "Evocation",
    classes: ["Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a piece of charcoal)",
    duration: "Concentration, up to 1 minute",
    description:
      "You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. When the wall appears, each creature in its area makes a Dexterity saving throw, taking 5d8 Fire damage on a failed save or half as much on a successful one.",
    higherLevel: "The damage increases by 1d8 for each spell slot level above 4.",
  },

  // Level 5 Spells
  {
    name: "Cone of Cold",
    level: 5,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (60-foot cone)",
    components: "V, S, M (a small crystal or glass cone)",
    duration: "Instantaneous",
    description:
      "A blast of cold air erupts from your hands. Each creature in a 60-foot Cone makes a Constitution saving throw, taking 8d8 Cold damage on a failed save or half as much on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.",
    higherLevel: "The damage increases by 1d8 for each spell slot level above 5.",
  },
  {
    name: "Greater Restoration",
    level: 5,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (diamond dust worth 100+ GP, which the spell consumes)",
    duration: "Instantaneous",
    description:
      "You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target's Exhaustion level by one, or end one of the following effects on the target: the Charmed or Petrified condition, a curse (including a cursed magic item), or any reduction to one of the target's ability scores or Hit Point maximum.",
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "90 feet",
    components: "V, S, M (a straight piece of iron)",
    duration: "Concentration, up to 1 minute",
    description:
      "Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target repeats the saving throw, ending the spell on itself on a success.",
    higherLevel: "You can target one additional creature for each spell slot level above 5.",
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius Sphere centered on that point. Each target regains Hit Points equal to 5d8 plus your spellcasting ability modifier. This spell has no effect on Constructs or Undead.",
    higherLevel: "The healing increases by 1d8 for each spell slot level above 5.",
  },
  {
    name: "Telekinesis",
    level: 5,
    school: "Transmutation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description:
      "You gain the ability to move or manipulate creatures or objects by thought. When you cast the spell, and as a Magic action on your later turns, you can exert your will on one creature or object that you can see within range. You can move a Huge or smaller creature or object up to 30 feet in any direction.",
  },
  {
    name: "Raise Dead",
    level: 5,
    school: "Necromancy",
    classes: ["Bard", "Cleric", "Paladin"],
    castingTime: "1 hour",
    range: "Touch",
    components: "V, S, M (a diamond worth 500+ GP, which the spell consumes)",
    duration: "Instantaneous",
    description:
      "You return a dead creature to life, provided that it has been dead no longer than 10 days. If the creature's soul is both willing and free to rejoin the body, the creature returns to life with 1 Hit Point. Coming back from the dead is an ordeal; the target takes a −4 penalty to all d20 Tests.",
  },

  // Level 6-9 Iconic Spells
  {
    name: "Chain Lightning",
    level: 6,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "150 feet",
    components: "V, S, M (three silver pins)",
    duration: "Instantaneous",
    description:
      "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. Each target makes a Dexterity saving throw, taking 10d8 Lightning damage on a failed save or half as much on a successful one.",
    higherLevel: "One additional bolt leaps from the first target to another target for each spell slot level above 6.",
  },
  {
    name: "Disintegrate",
    level: 6,
    school: "Transmutation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a lodestone and a pinch of dust)",
    duration: "Instantaneous",
    description:
      "A thin green ray springs from your pointing finger to a target that you can see within range. The target can be a creature, an object, or a magical barrier. A creature targeted by this spell makes a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 Force damage. If this damage reduces the creature to 0 Hit Points, it is disintegrated.",
    higherLevel: "The damage increases by 3d6 for each spell slot level above 6.",
  },
  {
    name: "Finger of Death",
    level: 7,
    school: "Necromancy",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target makes a Constitution saving throw, taking 7d8 + 30 Necrotic damage on a failed save or half as much on a successful one. A Humanoid killed by this spell rises at the start of your next turn as a Zombie that is under your control.",
  },
  {
    name: "Power Word Stun",
    level: 8,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "You speak a word of power that can overwhelm the mind of one creature you can see within range. If the target has 150 Hit Points or fewer, it has the Stunned condition. At the end of each of its turns, the Stunned target makes a Constitution saving throw, ending the effect on itself on a success.",
  },
  {
    name: "Power Word Kill",
    level: 9,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you chose has 100 Hit Points or fewer, it dies. Otherwise, the spell has no effect.",
  },
  {
    name: "Wish",
    level: 9,
    school: "Conjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description:
      "Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of level 8 or lower without needing to meet any requirements, including costly components.",
  },
]
