// ── First-party NPC encounter pool ───────────────────────────────────────────
// A curated, hand-authored set of roadside-encounter NPCs. Map "encounter"
// markers (Azgaar's "Random encounter" type) are dealt a DISTINCT NPC from this
// pool at import/adopt time — first-party, so we own the name + bio (no Deorum
// CC-BY-NC iframe, and the name actually exists offline).
//
// ⚠️ SERVER-ONLY. This module is imported ONLY by convex/ functions. Never import
// it into a client component: a `secret` field would then ship in the browser
// bundle and leak to players. The chosen NPC is COPIED onto the pin (minus name →
// the pin's name), and listLocations strips that copy for players (name only).
//
// Curated once, by hand, on purpose (the headless-bake lesson — see
// memory/azgaar_headless_bake.md): a fixed, reviewable artifact beats AI-at-seed
// (nondeterministic, samey, re-pays cost). Expand freely — just append; a campaign
// only ever spends ~7–15 at once, sampled without replacement.

export type PoolNpc = {
  name: string
  race: string
  occupation: string
  alignment: string
  appearance: string
  personality: string[]
  mannerisms: string
  voice: string
  motivation: string
  secret: string
  hook: string
}

export const NPC_POOL: PoolNpc[] = [
  {
    name: "Maren Holloway",
    race: "Human",
    occupation: "Travelling herbalist",
    alignment: "Neutral Good",
    appearance: "Weathered woman in her fifties, hands stained green, a mule laden with hanging bundles of dried plants.",
    personality: ["Patient", "Shrewd", "Maternal"],
    mannerisms: "Tastes a pinch of any new herb before speaking about it; calls everyone 'duck'.",
    voice: "Low and unhurried, with a rural burr.",
    motivation: "To find a rare moonflower said to grow only where someone has died of grief.",
    secret: "She poisoned her late husband — slowly, mercifully — at his own begging, and tells herself it was healing.",
    hook: "Will trade a potent remedy for an escort to a battlefield where the moonflower might bloom.",
  },
  {
    name: "Brakkar Stonefist",
    race: "Dwarf",
    occupation: "Out-of-work caravan guard",
    alignment: "Chaotic Neutral",
    appearance: "Broad, scarred, missing two fingers on his shield hand; sits sharpening an axe he can't afford to use.",
    personality: ["Gruff", "Loyal", "Proud"],
    mannerisms: "Spits before making a promise; counts coins twice.",
    voice: "Gravelled and clipped, every word a small grudge.",
    motivation: "To pay off the debt that cost him his last posting before his old captain finds him.",
    secret: "He fled the caravan he was guarding when bandits struck — the only survivor, and not by courage.",
    hook: "Offers his axe cheap to anyone heading the opposite direction from the road south.",
  },
  {
    name: "Sister Avelline",
    race: "Half-elf",
    occupation: "Wandering mendicant",
    alignment: "Lawful Good",
    appearance: "Young, road-dusty grey robes, a holy symbol worn smooth from handling, bare blistered feet.",
    personality: ["Earnest", "Stubborn", "Gentle"],
    mannerisms: "Blesses food before eating, even a stolen apple; flinches at raised voices.",
    voice: "Soft, careful, prone to long pauses while she chooses kind words.",
    motivation: "To walk to every shrine on the old pilgrim road and reconsecrate the abandoned ones.",
    secret: "Her faith is gone — she felt it leave a year ago — and she keeps walking hoping to find it again.",
    hook: "Asks the party to carry a sealed letter to a shrine she's too afraid to enter.",
  },
  {
    name: "Casso Veil",
    race: "Tiefling",
    occupation: "Card sharp",
    alignment: "Chaotic Neutral",
    appearance: "Lean, immaculate despite the dust, filed horns capped in tarnished silver, a deck always in hand.",
    personality: ["Charming", "Restless", "Cynical"],
    mannerisms: "Shuffles cards one-handed while talking; never sits with his back to a door.",
    voice: "Smooth and quick, laughter that never quite reaches the eyes.",
    motivation: "To win back a family heirloom he gambled away in a worse year.",
    secret: "The 'heirloom' is a contract — a devil holds his sister's name, and the deck is how he stalls.",
    hook: "Bets the party he can guess their road; if he wins, they hear him out about a job up north.",
  },
  {
    name: "Old Pemberton",
    race: "Human",
    occupation: "Retired tax collector",
    alignment: "Lawful Neutral",
    appearance: "Stooped, fussy, ink-stained cuffs, a ledger he no longer needs but can't put down.",
    personality: ["Meticulous", "Lonely", "Officious"],
    mannerisms: "Corrects people's grammar; itemizes everything, including a meal.",
    voice: "Reedy and precise, with a clerk's flat cadence.",
    motivation: "To deliver one last set of records to the capital and clear his old district's name.",
    secret: "The records prove a noble's fraud — and that Pemberton looked the other way for thirty years.",
    hook: "Hires guards for the road, vastly underpaying, and won't say what's in the locked case.",
  },
  {
    name: "Yelena Frost",
    race: "Human",
    occupation: "Fur trapper",
    alignment: "Neutral",
    appearance: "Wiry, wind-burned, wrapped in pelts, a longbow worn like a third limb.",
    personality: ["Taciturn", "Observant", "Self-reliant"],
    mannerisms: "Watches the treeline mid-conversation; whittles when thinking.",
    voice: "Quiet, economical, a northern drawl.",
    motivation: "To track the white wolf that's been emptying her snares — not to kill it, to understand it.",
    secret: "The 'wolf' walks on two legs some nights, and she's begun leaving it food.",
    hook: "Warns travellers off the north trail, then quietly hopes they'll go look anyway.",
  },
  {
    name: "Doral Quint",
    race: "Halfling",
    occupation: "Pie-cart cook",
    alignment: "Neutral Good",
    appearance: "Round, cheerful, flour to the elbows, a cart that smells better than anything for miles.",
    personality: ["Warm", "Gossipy", "Generous"],
    mannerisms: "Feeds people before asking their business; remembers every face.",
    voice: "Bright and rambling, always mid-story.",
    motivation: "To learn what happened to his brother, who took the same road two seasons back and never wrote.",
    secret: "He recognizes one of the party from a wanted poster and is deciding whether to say anything.",
    hook: "Gives away a free meal in exchange for news from the road, and listens very closely.",
  },
  {
    name: "Ironclad Vesh",
    race: "Warforged",
    occupation: "Masterless sentinel",
    alignment: "Lawful Neutral",
    appearance: "Tarnished plates, a faded regimental sigil, standing at a post that no longer exists.",
    personality: ["Dutiful", "Literal", "Searching"],
    mannerisms: "States the time and weather unprompted; salutes officers who died decades ago.",
    voice: "Even and resonant, like a bell with a crack in it.",
    motivation: "To find anyone who can issue it a new lawful order, having outlived its entire command.",
    secret: "Its last order was to hold a bridge 'until relieved' — the bridge is gone, and it still believes relief is coming.",
    hook: "Demands the password to pass a road that hasn't been a checkpoint in forty years.",
  },
  {
    name: "Lady Orsolya",
    race: "Human",
    occupation: "Disgraced noble",
    alignment: "Lawful Evil",
    appearance: "Elegant travelling clothes gone threadbare, jewellery sold down to one ring, chin always up.",
    personality: ["Imperious", "Calculating", "Resentful"],
    mannerisms: "Addresses commoners by their function, not their names; never says thank you.",
    voice: "Cultured, cold, with a duellist's precision.",
    motivation: "To reach a cousin's court and claw her way back to the standing her brother gambled away.",
    secret: "She arranged her brother's 'accident' — and it's the one thing she actually regrets.",
    hook: "Offers a fat purse on arrival (which she does not have) for protection to the next city.",
  },
  {
    name: "Tobble Ashwick",
    race: "Gnome",
    occupation: "Tinker",
    alignment: "Chaotic Good",
    appearance: "Goggles, a coat of pockets, a backpack that ticks and occasionally hisses steam.",
    personality: ["Excitable", "Distractible", "Kind"],
    mannerisms: "Finishes others' sentences with the wrong word; apologizes to his own inventions.",
    voice: "Rapid and squeaky, trailing into mutters.",
    motivation: "To field-test a self-winding lantern before a rival tinker patents the idea first.",
    secret: "The lantern works by trapping a tiny, miserable fire elemental he doesn't know how to free.",
    hook: "Begs the party to 'just hold this and tell me if it gets warm' on the road.",
  },
  {
    name: "Garran Mott",
    race: "Half-orc",
    occupation: "Itinerant gravedigger",
    alignment: "Neutral Good",
    appearance: "Huge, slow-moving, a spade over one shoulder, soil in the creases of his hands.",
    personality: ["Soft-spoken", "Honest", "Melancholy"],
    mannerisms: "Removes his cap for the dead, even strangers'; hums hymns off-key.",
    voice: "Deep and slow, gentler than his size suggests.",
    motivation: "To give a proper burial to the unclaimed bodies left along the war road.",
    secret: "One of those bodies was a man he killed in self-defence, and he's been burying penance ever since.",
    hook: "Asks for help digging before dark, and tells the truth about how the man died if asked kindly.",
  },
  {
    name: "Esme Tarrow",
    race: "Human",
    occupation: "Travelling midwife",
    alignment: "Neutral Good",
    appearance: "Practical, sharp-eyed, a satchel of clean linen and dark little bottles, perpetually tired.",
    personality: ["Blunt", "Compassionate", "Unflappable"],
    mannerisms: "Checks your pulse if you so much as cough; suffers no fools.",
    voice: "Brisk and dry, kinder underneath than on the surface.",
    motivation: "To reach a remote village where a birth has gone wrong before it's too late.",
    secret: "She's fleeing a town that named her a witch for a child she couldn't save.",
    hook: "Flags the party down, frantic, needing fast horses or fast feet — now.",
  },
  {
    name: "Caelum Dree",
    race: "Elf",
    occupation: "Exiled astronomer",
    alignment: "Neutral",
    appearance: "Ageless, ink-stained, a brass star-chart rolled under one arm, eyes always half on the sky.",
    personality: ["Distant", "Precise", "Haunted"],
    mannerisms: "Names constellations under his breath; measures distances by holding up his thumb.",
    voice: "Quiet, formal, oddly musical.",
    motivation: "To reach high ground before a conjunction he's waited two centuries to witness.",
    secret: "His charts predict the conjunction heralds a disaster, and he can't decide whether to warn anyone.",
    hook: "Asks the way to the nearest peak and grows agitated if told the weather will turn.",
  },
  {
    name: "Rook",
    race: "Human",
    occupation: "Self-styled road minstrel",
    alignment: "Chaotic Good",
    appearance: "Young, threadbare finery, a battered lute with one too few strings, a hopeful grin.",
    personality: ["Irrepressible", "Vain", "Brave"],
    mannerisms: "Narrates his own life in third person; invents heroic verses about people he just met.",
    voice: "Theatrical, loud, cracking on the high notes.",
    motivation: "To witness a real adventure worth a real song and finally have something true to sing.",
    secret: "Every song in his repertoire is stolen from a dead bard whose name he's let everyone forget.",
    hook: "Offers to travel with the party 'for the ballad', and is a far better lookout than musician.",
  },
  {
    name: "Mother Vask",
    race: "Human",
    occupation: "Hedge witch",
    alignment: "Chaotic Neutral",
    appearance: "Ancient, beady-eyed, a shawl of crow feathers, a cottage on no map that's always just off the road.",
    personality: ["Cryptic", "Sly", "Fair"],
    mannerisms: "Answers questions with questions; pays debts in riddles and favours.",
    voice: "Cackling and sing-song, sharper when she drops the act.",
    motivation: "To collect on old bargains before the year turns and the terms change.",
    secret: "She is far younger than she appears and ages herself with a glamour to be left alone.",
    hook: "Offers a true answer to one question — for a price chosen later, by her.",
  },
  {
    name: "Dunmar Pell",
    race: "Dwarf",
    occupation: "Failed prospector",
    alignment: "Neutral",
    appearance: "Sunburnt, gaunt, a pan and pick worth more than the dust in his pouch, eyes too bright.",
    personality: ["Optimistic", "Obsessive", "Talkative"],
    mannerisms: "Shows everyone his 'almost' nuggets; swears the next claim is the one.",
    voice: "Fast, hoarse, feverish with hope.",
    motivation: "To reach a creek a dying man swore ran gold, before anyone else hears the rumour.",
    secret: "He already found the creek. It ran with something that wasn't gold, and now it follows him.",
    hook: "Tries to recruit partners for a claim, splitting shares he hasn't earned yet.",
  },
  {
    name: "Naia Storm-Crow",
    race: "Aarakocra",
    occupation: "Sky courier",
    alignment: "Chaotic Good",
    appearance: "Storm-grey feathers, a satchel of waxed letters, a wing that doesn't fold quite right.",
    personality: ["Free-spirited", "Curious", "Reckless"],
    mannerisms: "Perches rather than sits; collects shiny buttons; underestimates ground distances.",
    voice: "Bright, whistling, with the cadence of wind.",
    motivation: "To deliver a letter to a lighthouse before a wedding that the letter will probably stop.",
    secret: "She read the letter. She's deciding whether some messages are better lost.",
    hook: "Lands hard near the party, injured wing, needing the letter carried the last leg by road.",
  },
  {
    name: "Severin Lowe",
    race: "Human",
    occupation: "Plague doctor",
    alignment: "Lawful Neutral",
    appearance: "Beaked mask, waxed coat, a cane that taps a careful rhythm, never quite close enough to touch.",
    personality: ["Detached", "Methodical", "Quietly kind"],
    mannerisms: "Burns sage before entering anywhere; keeps a careful arm's length from the living.",
    voice: "Muffled and measured behind the mask.",
    motivation: "To trace a sickness back along the trade road to wherever it began.",
    secret: "He is immune because he's already dead in every way that matters — a lich's failed first attempt.",
    hook: "Quarantines a stretch of road and needs supplies fetched from beyond the line.",
  },
  {
    name: "Pip Quickfellow",
    race: "Halfling",
    occupation: "Pickpocket turned guide",
    alignment: "Chaotic Good",
    appearance: "Small, quick, too many pockets, a grin that's apologizing in advance.",
    personality: ["Nimble", "Guilty", "Eager to please"],
    mannerisms: "Returns things before you notice they're gone; can't stop fidgeting.",
    voice: "Quick, chirpy, drops to a whisper near guards.",
    motivation: "To go straight by guiding travellers safely — and to outrun his old crew's leader.",
    secret: "He still has the ring he lifted from that leader, and it's why she's hunting him.",
    hook: "Offers to guide the party through the badlands cheap, glancing over his shoulder the whole way.",
  },
  {
    name: "Hagen Roard",
    race: "Human",
    occupation: "Bounty hunter",
    alignment: "Lawful Neutral",
    appearance: "Hard-faced, road-leathered, a coat heavy with manacles and folded warrants.",
    personality: ["Patient", "Fair", "Unsentimental"],
    mannerisms: "Studies faces a beat too long; reads warrants aloud like scripture.",
    voice: "Flat, even, no threat in it because none is needed.",
    motivation: "To bring in a mark he's chased for a year, alive, exactly as the law requires.",
    secret: "The mark is innocent — Hagen has known for months — and the warrant pays too well to question.",
    hook: "Shows the party a warrant and asks, mildly, whether they've seen the face.",
  },
  {
    name: "Wisp",
    race: "Changeling",
    occupation: "Information broker",
    alignment: "True Neutral",
    appearance: "Forgettable on purpose — a face you can't quite describe a minute after seeing it.",
    personality: ["Watchful", "Noncommittal", "Precise"],
    mannerisms: "Mirrors your posture; never gives a name twice; pays for stories with stories.",
    voice: "Pleasant, neutral, hard to place.",
    motivation: "To gather one specific secret valuable enough to buy a life off the market for good.",
    secret: "The life being bought back is their own — they sold their true name years ago.",
    hook: "Knows something the party needs and trades it for a small, strange errand.",
  },
  {
    name: "Berta Oldoak",
    race: "Firbolg",
    occupation: "Wandering shepherd",
    alignment: "Neutral Good",
    appearance: "Towering, mossy-haired, a flock that's mostly sheep and one creature that very much isn't.",
    personality: ["Gentle", "Slow to anger", "Protective"],
    mannerisms: "Speaks to her animals as equals; counts the flock obsessively.",
    voice: "Deep, rumbling, surprisingly shy.",
    motivation: "To find new pasture before winter, away from the road's noise and the hunters.",
    secret: "The 'lamb' she guards most fiercely is a young creature from the Feywild she's hiding.",
    hook: "Blocks the road with her flock and won't move them until she trusts the party's intent.",
  },
  {
    name: "Aldric Venn",
    race: "Human",
    occupation: "Deserter",
    alignment: "Neutral",
    appearance: "A soldier's bearing under farmer's clothes, a sword he keeps wrapped, eyes that don't rest.",
    personality: ["Wary", "Haunted", "Decent"],
    mannerisms: "Sleeps facing the door; flinches at horns and drums.",
    voice: "Low, careful, soldier's economy of words.",
    motivation: "To reach a border he can't be followed across and start a life with no banners in it.",
    secret: "He didn't desert from cowardice — he refused an order to burn a village, and they'll hang him for it.",
    hook: "Asks the safest road away from the garrison and pays in a soldier's hard-won coin.",
  },
  {
    name: "Quillon Sage",
    race: "Elf",
    occupation: "Book peddler",
    alignment: "Chaotic Good",
    appearance: "Dapper, ink-smudged, a cart of stacked books lashed against the rain, spectacles on a chain.",
    personality: ["Erudite", "Mischievous", "Sentimental"],
    mannerisms: "Quotes books at people; can't resist a marginal note in anything he sells.",
    voice: "Warm, animated, given to tangents.",
    motivation: "To find a buyer brave enough for one particular banned book before the censors find him.",
    secret: "He wrote the banned book himself, under a name the authorities have started to crave very badly.",
    hook: "Presses a 'harmless' book on the party, then asks them to hold it 'just till the next town'.",
  },
  {
    name: "Skarn the Mild",
    race: "Goliath",
    occupation: "Reformed raider",
    alignment: "Lawful Good",
    appearance: "Mountain-broad, old tattoos half-scratched out, a hand-carved holy symbol on a leather cord.",
    personality: ["Calm", "Devout", "Burdened"],
    mannerisms: "Apologizes for his size in doorways; refuses to raise his voice.",
    voice: "Quiet thunder, slow and deliberate.",
    motivation: "To repay every village his old band raided, one good deed at a time.",
    secret: "One village he can never repay — there's no one left in it — and he saves his hardest work for its ruins.",
    hook: "Offers his strength for free to anyone heading toward the eastern ruins.",
  },
  {
    name: "Fenna Bright",
    race: "Half-elf",
    occupation: "Travelling tooth-drawer",
    alignment: "Neutral",
    appearance: "Cheerful, blood-flecked apron, a tray of alarming pliers, a smile with a gold tooth.",
    personality: ["Jolly", "Morbid", "Practical"],
    mannerisms: "Appraises everyone's teeth; tells gory stories to relax patients (it doesn't work).",
    voice: "Loud, friendly, far too casual about pain.",
    motivation: "To save enough to open a real surgery and stop working out of a cart.",
    secret: "She sells the gold teeth she pulls from the dead, and not all of them were dead first.",
    hook: "Offers to pull a 'troublesome' tooth nobody asked about, for a very fair price.",
  },
  {
    name: "Corvin Ashe",
    race: "Tiefling",
    occupation: "Funeral-mask carver",
    alignment: "Neutral Good",
    appearance: "Soot-dark skin, ember eyes, a satchel of pale carved masks that seem to watch you back.",
    personality: ["Solemn", "Empathetic", "Private"],
    mannerisms: "Studies faces to carve them; speaks of the dead in the present tense.",
    voice: "Hushed and grave, with unexpected warmth.",
    motivation: "To carry a finished mask to a grave he was paid to honour but never told whose it is.",
    secret: "The masks let him briefly hear the last words of whoever they're carved for — and he's addicted to it.",
    hook: "Asks the party to help him find a grave marked only by a symbol he sketches in the dirt.",
  },
  {
    name: "Goodwife Trill",
    race: "Human",
    occupation: "Egg-and-cheese seller",
    alignment: "Neutral Good",
    appearance: "Plump, rosy, a basket of speckled eggs and waxed rounds, a shawl mended a dozen times.",
    personality: ["Chatty", "Nosy", "Big-hearted"],
    mannerisms: "Knows everyone's business and shares it freely; presses food on strangers.",
    voice: "Sing-song, motherly, relentlessly cheerful.",
    motivation: "To get to market and back before her husband notices how much she's giving away.",
    secret: "She's been quietly feeding a 'beggar' in the woods who is in fact a wanted fugitive she's grown fond of.",
    hook: "Trades news for company on the road and lets slip exactly the rumour the party needs.",
  },
  {
    name: "Marshal Crane",
    race: "Human",
    occupation: "Circuit judge",
    alignment: "Lawful Neutral",
    appearance: "Severe, black-clad, a chain of office, a clerk's box of writs balanced on the saddle.",
    personality: ["Stern", "Incorruptible", "Weary"],
    mannerisms: "Weighs every word as testimony; refuses gifts of any kind.",
    voice: "Dry, exact, courtroom-cadenced.",
    motivation: "To reach the next assize town and clear a docket of cases before the harvest unrest spreads.",
    secret: "He let a guilty man hang once on bad evidence and now rules so harshly he creates new injustices.",
    hook: "Deputizes the party (whether they like it or not) to escort a prisoner to trial.",
  },
  {
    name: "Little Owl",
    race: "Human",
    occupation: "Feral orphan",
    alignment: "Chaotic Neutral",
    appearance: "A ragged child of indeterminate age, too quiet, too quick, eyes that miss nothing.",
    personality: ["Wary", "Feral", "Fiercely loyal once won"],
    mannerisms: "Hoards food in pockets; vanishes when voices rise; never says please.",
    voice: "Rare and rusty, words half-remembered.",
    motivation: "To survive the road and keep the younger ones she hides from the slavers fed.",
    secret: "She's been leading travellers into an ambush to buy the slavers' silence — and hates herself for it.",
    hook: "Tugs a sleeve, points down a side trail, says only 'this way' — and means more than one thing by it.",
  },
  {
    name: "Bram Tolliver",
    race: "Human",
    occupation: "Ferryman",
    alignment: "True Neutral",
    appearance: "Knotted with muscle, river-damp, a pole worn smooth, a coin always tucked behind his ear.",
    personality: ["Laconic", "Superstitious", "Fair"],
    mannerisms: "Won't cross at dusk; flips a coin to decide anything he doesn't care about.",
    voice: "Slow, river-smoothed, fond of weather-talk.",
    motivation: "To keep the crossing running and never, ever cross after dark again.",
    secret: "Something in the river takes a passenger each year, and Bram chooses who by who tips worst.",
    hook: "Names a fair fare to cross — and a strange condition: all aboard before the sun touches the water.",
  },
  {
    name: "Vex Underholt",
    race: "Drow",
    occupation: "Surface exile",
    alignment: "Chaotic Good",
    appearance: "Cloaked against the light, ash-grey skin, hands raw from work she was never raised to do.",
    personality: ["Guarded", "Dry-witted", "Proud"],
    mannerisms: "Squints in daylight; tests food for poison out of pure habit.",
    voice: "Low, accented, with a blade's edge of sarcasm.",
    motivation: "To prove a surface life is possible before the cold or the prejudice kills her first.",
    secret: "Her house didn't exile her — she fled after warning a surface town of a raid, and they'd kill her for the warning.",
    hook: "Trades hard-won survival lore for a night's safe watch, expecting to be turned away.",
  },
  {
    name: "Father Greaves",
    race: "Human",
    occupation: "Travelling confessor",
    alignment: "Lawful Good",
    appearance: "Stout, kind-faced, a portable shrine on his back, knees gone from a lifetime of kneeling.",
    personality: ["Forgiving", "Tireless", "Perceptive"],
    mannerisms: "Hears confession from anyone, including bandits; never repeats a word of it.",
    voice: "Round, gentle, endlessly reassuring.",
    motivation: "To reach a condemned man's cell and offer last rites before the rope.",
    secret: "A confession he heard names the real killer — and the seal of his office forbids him to ever tell.",
    hook: "Asks for swift company to the gaol-town, growing more troubled the closer they get.",
  },
  {
    name: "Thessaly Dunn",
    race: "Human",
    occupation: "Cartographer",
    alignment: "Neutral Good",
    appearance: "Sun-squinting, satchel of rolled maps, a spyglass, boots resoled more than once.",
    personality: ["Curious", "Precise", "Adventurous"],
    mannerisms: "Sketches everything; argues with her own old maps; names hills she passes.",
    voice: "Quick, enthusiastic, prone to direction-giving nobody asked for.",
    motivation: "To map the one valley every existing chart leaves suspiciously blank.",
    secret: "The valley is blank on purpose — the last cartographer who filled it in disappeared, and she has his notes.",
    hook: "Hires guides into the unmapped valley, downplaying just how many others didn't come back.",
  },
  {
    name: "Mungo Baskin",
    race: "Halfling",
    occupation: "Travelling brewer",
    alignment: "Chaotic Good",
    appearance: "Barrel-shaped, foam in his whiskers, a cart of clinking kegs and a tasting-cup on a string.",
    personality: ["Boisterous", "Generous", "Loyal"],
    mannerisms: "Toasts everything; judges people by how they hold a cup; sings when drunk (often).",
    voice: "Booming, hearty, sloppier as the day goes on.",
    motivation: "To deliver a wedding ale to a village three days off before it sours.",
    secret: "A keg in the cart isn't ale — it's a dwarf's ashes he's smuggling home, disguised among the barrels.",
    hook: "Shares a free cup, then sheepishly asks for muscle to guard the cart the rest of the way.",
  },
  {
    name: "The Veiled Lady",
    race: "Unknown",
    occupation: "Toll-keeper of a bridge that shouldn't exist",
    alignment: "Lawful Neutral",
    appearance: "A still figure in grey veils at a bridge no map shows, voice the only proof there's a person beneath.",
    personality: ["Implacable", "Courteous", "Ancient"],
    mannerisms: "Asks each traveller the same three questions; never repeats herself; never blinks (if she blinks).",
    voice: "Soft, formal, seeming to come from just behind you.",
    motivation: "To collect the toll the old pact demands and let no one cross who cannot pay it.",
    secret: "The toll is never coin — it's a memory, taken on crossing, and she is made entirely of the ones she's kept.",
    hook: "Bars a shortcut over her bridge until each traveller answers truly what they'd give to cross.",
  },
]
