// ── First-party NPC encounter pool ───────────────────────────────────────────
// A curated, hand-authored set of roadside-encounter NPCs. Map "encounter"
// markers (Azgaar's "Random encounter" type) are dealt a DISTINCT NPC from this
// pool at import/adopt time — first-party, so we own the name + bio (no Deorum
// CC-BY-NC iframe, and the name actually exists offline).
//
// ⚠️ SERVER-ONLY. This module is imported ONLY by convex/ functions. Never import
// it into a client component: a `secret` field would then ship in the browser
// bundle and leak to players. The chosen NPC is COPIED onto the pin (minus name →
// the pin's name), and listLocations strips that copy for players (name only).
//
// Curated once, by hand, on purpose (the headless-bake lesson — see
// memory/azgaar_headless_bake.md): a fixed, reviewable artifact beats AI-at-seed
// (nondeterministic, samey, re-pays cost). Expand freely — just append; a campaign
// only ever spends ~7–15 at once, sampled without replacement.

export type PoolNpc = {
  name: string
  race: string
  occupation: string
  alignment: string
  appearance: string
  personality: string[]
  mannerisms: string
  voice: string
  motivation: string
  secret: string
  hook: string
}

export const NPC_POOL: PoolNpc[] = [
  {
    name: "Maren Holloway",
    race: "Human",
    occupation: "Travelling herbalist",
    alignment: "Neutral Good",
    appearance: "Weathered woman in her fifties, hands stained green, a mule laden with hanging bundles of dried plants.",
    personality: ["Patient", "Shrewd", "Maternal"],
    mannerisms: "Tastes a pinch of any new herb before speaking about it; calls everyone 'duck'.",
    voice: "Low and unhurried, with a rural burr.",
    motivation: "To find a rare moonflower said to grow only where someone has died of grief.",
    secret: "She poisoned her late husband — slowly, mercifully — at his own begging, and tells herself it was healing.",
    hook: "Will trade a potent remedy for an escort to a battlefield where the moonflower might bloom.",
  },
  {
    name: "Brakkar Stonefist",
    race: "Dwarf",
    occupation: "Out-of-work caravan guard",
    alignment: "Chaotic Neutral",
    appearance: "Broad, scarred, missing two fingers on his shield hand; sits sharpening an axe he can't afford to use.",
    personality: ["Gruff", "Loyal", "Proud"],
    mannerisms: "Spits before making a promise; counts coins twice.",
    voice: "Gravelled and clipped, every word a small grudge.",
    motivation: "To pay off the debt that cost him his last posting before his old captain finds him.",
    secret: "He fled the caravan he was guarding when bandits struck — the only survivor, and not by courage.",
    hook: "Offers his axe cheap to anyone heading the opposite direction from the road south.",
  },
  {
    name: "Sister Avelline",
    race: "Half-elf",
    occupation: "Wandering mendicant",
    alignment: "Lawful Good",
    appearance: "Young, road-dusty grey robes, a holy symbol worn smooth from handling, bare blistered feet.",
    personality: ["Earnest", "Stubborn", "Gentle"],
    mannerisms: "Blesses food before eating, even a stolen apple; flinches at raised voices.",
    voice: "Soft, careful, prone to long pauses while she chooses kind words.",
    motivation: "To walk to every shrine on the old pilgrim road and reconsecrate the abandoned ones.",
    secret: "Her faith is gone — she felt it leave a year ago — and she keeps walking hoping to find it again.",
    hook: "Asks the party to carry a sealed letter to a shrine she's too afraid to enter.",
  },
  {
    name: "Casso Veil",
    race: "Tiefling",
    occupation: "Card sharp",
    alignment: "Chaotic Neutral",
    appearance: "Lean, immaculate despite the dust, filed horns capped in tarnished silver, a deck always in hand.",
    personality: ["Charming", "Restless", "Cynical"],
    mannerisms: "Shuffles cards one-handed while talking; never sits with his back to a door.",
    voice: "Smooth and quick, laughter that never quite reaches the eyes.",
    motivation: "To win back a family heirloom he gambled away in a worse year.",
    secret: "The 'heirloom' is a contract — a devil holds his sister's name, and the deck is how he stalls.",
    hook: "Bets the party he can guess their road; if he wins, they hear him out about a job up north.",
  },
  {
    name: "Old Pemberton",
    race: "Human",
    occupation: "Retired tax collector",
    alignment: "Lawful Neutral",
    appearance: "Stooped, fussy, ink-stained cuffs, a ledger he no longer needs but can't put down.",
    personality: ["Meticulous", "Lonely", "Officious"],
    mannerisms: "Corrects people's grammar; itemizes everything, including a meal.",
    voice: "Reedy and precise, with a clerk's flat cadence.",
    motivation: "To deliver one last set of records to the capital and clear his old district's name.",
    secret: "The records prove a noble's fraud — and that Pemberton looked the other way for thirty years.",
    hook: "Hires guards for the road, vastly underpaying, and won't say what's in the locked case.",
  },
  {
    name: "Yelena Frost",
    race: "Human",
    occupation: "Fur trapper",
    alignment: "Neutral",
    appearance: "Wiry, wind-burned, wrapped in pelts, a longbow worn like a third limb.",
    personality: ["Taciturn", "Observant", "Self-reliant"],
    mannerisms: "Watches the treeline mid-conversation; whittles when thinking.",
    voice: "Quiet, economical, a northern drawl.",
    motivation: "To track the white wolf that's been emptying her snares — not to kill it, to understand it.",
    secret: "The 'wolf' walks on two legs some nights, and she's begun leaving it food.",
    hook: "Warns travellers off the north trail, then quietly hopes they'll go look anyway.",
  },
  {
    name: "Doral Quint",
    race: "Halfling",
    occupation: "Pie-cart cook",
    alignment: "Neutral Good",
    appearance: "Round, cheerful, flour to the elbows, a cart that smells better than anything for miles.",
    personality: ["Warm", "Gossipy", "Generous"],
    mannerisms: "Feeds people before asking their business; remembers every face.",
    voice: "Bright and rambling, always mid-story.",
    motivation: "To learn what happened to his brother, who took the same road two seasons back and never wrote.",
    secret: "He recognizes one of the party from a wanted poster and is deciding whether to say anything.",
    hook: "Gives away a free meal in exchange for news from the road, and listens very closely.",
  },
  {
    name: "Ironclad Vesh",
    race: "Warforged",
    occupation: "Masterless sentinel",
    alignment: "Lawful Neutral",
    appearance: "Tarnished plates, a faded regimental sigil, standing at a post that no longer exists.",
    personality: ["Dutiful", "Literal", "Searching"],
    mannerisms: "States the time and weather unprompted; salutes officers who died decades ago.",
    voice: "Even and resonant, like a bell with a crack in it.",
    motivation: "To find anyone who can issue it a new lawful order, having outlived its entire command.",
    secret: "Its last order was to hold a bridge 'until relieved' — the bridge is gone, and it still believes relief is coming.",
    hook: "Demands the password to pass a road that hasn't been a checkpoint in forty years.",
  },
  {
    name: "Lady Orsolya",
    race: "Human",
    occupation: "Disgraced noble",
    alignment: "Lawful Evil",
    appearance: "Elegant travelling clothes gone threadbare, jewellery sold down to one ring, chin always up.",
    personality: ["Imperious", "Calculating", "Resentful"],
    mannerisms: "Addresses commoners by their function, not their names; never says thank you.",
    voice: "Cultured, cold, with a duellist's precision.",
    motivation: "To reach a cousin's court and claw her way back to the standing her brother gambled away.",
    secret: "She arranged her brother's 'accident' — and it's the one thing she actually regrets.",
    hook: "Offers a fat purse on arrival (which she does not have) for protection to the next city.",
  },
  {
    name: "Tobble Ashwick",
    race: "Gnome",
    occupation: "Tinker",
    alignment: "Chaotic Good",
    appearance: "Goggles, a coat of pockets, a backpack that ticks and occasionally hisses steam.",
    personality: ["Excitable", "Distractible", "Kind"],
    mannerisms: "Finishes others' sentences with the wrong word; apologizes to his own inventions.",
    voice: "Rapid and squeaky, trailing into mutters.",
    motivation: "To field-test a self-winding lantern before a rival tinker patents the idea first.",
    secret: "The lantern works by trapping a tiny, miserable fire elemental he doesn't know how to free.",
    hook: "Begs the party to 'just hold this and tell me if it gets warm' on the road.",
  },
  {
    name: "Garran Mott",
    race: "Half-orc",
    occupation: "Itinerant gravedigger",
    alignment: "Neutral Good",
    appearance: "Huge, slow-moving, a spade over one shoulder, soil in the creases of his hands.",
    personality: ["Soft-spoken", "Honest", "Melancholy"],
    mannerisms: "Removes his cap for the dead, even strangers'; hums hymns off-key.",
    voice: "Deep and slow, gentler than his size suggests.",
    motivation: "To give a proper burial to the unclaimed bodies left along the war road.",
    secret: "One of those bodies was a man he killed in self-defence, and he's been burying penance ever since.",
    hook: "Asks for help digging before dark, and tells the truth about how the man died if asked kindly.",
  },
  {
    name: "Esme Tarrow",
    race: "Human",
    occupation: "Travelling midwife",
    alignment: "Neutral Good",
    appearance: "Practical, sharp-eyed, a satchel of clean linen and dark little bottles, perpetually tired.",
    personality: ["Blunt", "Compassionate", "Unflappable"],
    mannerisms: "Checks your pulse if you so much as cough; suffers no fools.",
    voice: "Brisk and dry, kinder underneath than on the surface.",
    motivation: "To reach a remote village where a birth has gone wrong before it's too late.",
    secret: "She's fleeing a town that named her a witch for a child she couldn't save.",
    hook: "Flags the party down, frantic, needing fast horses or fast feet — now.",
  },
  {
    name: "Caelum Dree",
    race: "Elf",
    occupation: "Exiled astronomer",
    alignment: "Neutral",
    appearance: "Ageless, ink-stained, a brass star-chart rolled under one arm, eyes always half on the sky.",
    personality: ["Distant", "Precise", "Haunted"],
    mannerisms: "Names constellations under his breath; measures distances by holding up his thumb.",
    voice: "Quiet, formal, oddly musical.",
    motivation: "To reach high ground before a conjunction he's waited two centuries to witness.",
    secret: "His charts predict the conjunction heralds a disaster, and he can't decide whether to warn anyone.",
    hook: "Asks the way to the nearest peak and grows agitated if told the weather will turn.",
  },
  {
    name: "Rook",
    race: "Human",
    occupation: "Self-styled road minstrel",
    alignment: "Chaotic Good",
    appearance: "Young, threadbare finery, a battered lute with one too few strings, a hopeful grin.",
    personality: ["Irrepressible", "Vain", "Brave"],
    mannerisms: "Narrates his own life in third person; invents heroic verses about people he just met.",
    voice: "Theatrical, loud, cracking on the high notes.",
    motivation: "To witness a real adventure worth a real song and finally have something true to sing.",
    secret: "Every song in his repertoire is stolen from a dead bard whose name he's let everyone forget.",
    hook: "Offers to travel with the party 'for the ballad', and is a far better lookout than musician.",
  },
  {
    name: "Mother Vask",
    race: "Human",
    occupation: "Hedge witch",
    alignment: "Chaotic Neutral",
    appearance: "Ancient, beady-eyed, a shawl of crow feathers, a cottage on no map that's always just off the road.",
    personality: ["Cryptic", "Sly", "Fair"],
    mannerisms: "Answers questions with questions; pays debts in riddles and favours.",
    voice: "Cackling and sing-song, sharper when she drops the act.",
    motivation: "To collect on old bargains before the year turns and the terms change.",
    secret: "She is far younger than she appears and ages herself with a glamour to be left alone.",
    hook: "Offers a true answer to one question — for a price chosen later, by her.",
  },
  {
    name: "Dunmar Pell",
    race: "Dwarf",
    occupation: "Failed prospector",
    alignment: "Neutral",
    appearance: "Sunburnt, gaunt, a pan and pick worth more than the dust in his pouch, eyes too bright.",
    personality: ["Optimistic", "Obsessive", "Talkative"],
    mannerisms: "Shows everyone his 'almost' nuggets; swears the next claim is the one.",
    voice: "Fast, hoarse, feverish with hope.",
    motivation: "To reach a creek a dying man swore ran gold, before anyone else hears the rumour.",
    secret: "He already found the creek. It ran with something that wasn't gold, and now it follows him.",
    hook: "Tries to recruit partners for a claim, splitting shares he hasn't earned yet.",
  },
  {
    name: "Naia Storm-Crow",
    race: "Aarakocra",
    occupation: "Sky courier",
    alignment: "Chaotic Good",
    appearance: "Storm-grey feathers, a satchel of waxed letters, a wing that doesn't fold quite right.",
    personality: ["Free-spirited", "Curious", "Reckless"],
    mannerisms: "Perches rather than sits; collects shiny buttons; underestimates ground distances.",
    voice: "Bright, whistling, with the cadence of wind.",
    motivation: "To deliver a letter to a lighthouse before a wedding that the letter will probably stop.",
    secret: "She read the letter. She's deciding whether some messages are better lost.",
    hook: "Lands hard near the party, injured wing, needing the letter carried the last leg by road.",
  },
  {
    name: "Severin Lowe",
    race: "Human",
    occupation: "Plague doctor",
    alignment: "Lawful Neutral",
    appearance: "Beaked mask, waxed coat, a cane that taps a careful rhythm, never quite close enough to touch.",
    personality: ["Detached", "Methodical", "Quietly kind"],
    mannerisms: "Burns sage before entering anywhere; keeps a careful arm's length from the living.",
    voice: "Muffled and measured behind the mask.",
    motivation: "To trace a sickness back along the trade road to wherever it began.",
    secret: "He is immune because he's already dead in every way that matters — a lich's failed first attempt.",
    hook: "Quarantines a stretch of road and needs supplies fetched from beyond the line.",
  },
  {
    name: "Pip Quickfellow",
    race: "Halfling",
    occupation: "Pickpocket turned guide",
    alignment: "Chaotic Good",
    appearance: "Small, quick, too many pockets, a grin that's apologizing in advance.",
    personality: ["Nimble", "Guilty", "Eager to please"],
    mannerisms: "Returns things before you notice they're gone; can't stop fidgeting.",
    voice: "Quick, chirpy, drops to a whisper near guards.",
    motivation: "To go straight by guiding travellers safely — and to outrun his old crew's leader.",
    secret: "He still has the ring he lifted from that leader, and it's why she's hunting him.",
    hook: "Offers to guide the party through the badlands cheap, glancing over his shoulder the whole way.",
  },
  {
    name: "Hagen Roard",
    race: "Human",
    occupation: "Bounty hunter",
    alignment: "Lawful Neutral",
    appearance: "Hard-faced, road-leathered, a coat heavy with manacles and folded warrants.",
    personality: ["Patient", "Fair", "Unsentimental"],
    mannerisms: "Studies faces a beat too long; reads warrants aloud like scripture.",
    voice: "Flat, even, no threat in it because none is needed.",
    motivation: "To bring in a mark he's chased for a year, alive, exactly as the law requires.",
    secret: "The mark is innocent — Hagen has known for months — and the warrant pays too well to question.",
    hook: "Shows the party a warrant and asks, mildly, whether they've seen the face.",
  },
  {
    name: "Wisp",
    race: "Changeling",
    occupation: "Information broker",
    alignment: "True Neutral",
    appearance: "Forgettable on purpose — a face you can't quite describe a minute after seeing it.",
    personality: ["Watchful", "Noncommittal", "Precise"],
    mannerisms: "Mirrors your posture; never gives a name twice; pays for stories with stories.",
    voice: "Pleasant, neutral, hard to place.",
    motivation: "To gather one specific secret valuable enough to buy a life off the market for good.",
    secret: "The life being bought back is their own — they sold their true name years ago.",
    hook: "Knows something the party needs and trades it for a small, strange errand.",
  },
  {
    name: "Berta Oldoak",
    race: "Firbolg",
    occupation: "Wandering shepherd",
    alignment: "Neutral Good",
    appearance: "Towering, mossy-haired, a flock that's mostly sheep and one creature that very much isn't.",
    personality: ["Gentle", "Slow to anger", "Protective"],
    mannerisms: "Speaks to her animals as equals; counts the flock obsessively.",
    voice: "Deep, rumbling, surprisingly shy.",
    motivation: "To find new pasture before winter, away from the road's noise and the hunters.",
    secret: "The 'lamb' she guards most fiercely is a young creature from the Feywild she's hiding.",
    hook: "Blocks the road with her flock and won't move them until she trusts the party's intent.",
  },
  {
    name: "Aldric Venn",
    race: "Human",
    occupation: "Deserter",
    alignment: "Neutral",
    appearance: "A soldier's bearing under farmer's clothes, a sword he keeps wrapped, eyes that don't rest.",
    personality: ["Wary", "Haunted", "Decent"],
    mannerisms: "Sleeps facing the door; flinches at horns and drums.",
    voice: "Low, careful, soldier's economy of words.",
    motivation: "To reach a border he can't be followed across and start a life with no banners in it.",
    secret: "He didn't desert from cowardice — he refused an order to burn a village, and they'll hang him for it.",
    hook: "Asks the safest road away from the garrison and pays in a soldier's hard-won coin.",
  },
  {
    name: "Quillon Sage",
    race: "Elf",
    occupation: "Book peddler",
    alignment: "Chaotic Good",
    appearance: "Dapper, ink-smudged, a cart of stacked books lashed against the rain, spectacles on a chain.",
    personality: ["Erudite", "Mischievous", "Sentimental"],
    mannerisms: "Quotes books at people; can't resist a marginal note in anything he sells.",
    voice: "Warm, animated, given to tangents.",
    motivation: "To find a buyer brave enough for one particular banned book before the censors find him.",
    secret: "He wrote the banned book himself, under a name the authorities have started to crave very badly.",
    hook: "Presses a 'harmless' book on the party, then asks them to hold it 'just till the next town'.",
  },
  {
    name: "Skarn the Mild",
    race: "Goliath",
    occupation: "Reformed raider",
    alignment: "Lawful Good",
    appearance: "Mountain-broad, old tattoos half-scratched out, a hand-carved holy symbol on a leather cord.",
    personality: ["Calm", "Devout", "Burdened"],
    mannerisms: "Apologizes for his size in doorways; refuses to raise his voice.",
    voice: "Quiet thunder, slow and deliberate.",
    motivation: "To repay every village his old band raided, one good deed at a time.",
    secret: "One village he can never repay — there's no one left in it — and he saves his hardest work for its ruins.",
    hook: "Offers his strength for free to anyone heading toward the eastern ruins.",
  },
  {
    name: "Fenna Bright",
    race: "Half-elf",
    occupation: "Travelling tooth-drawer",
    alignment: "Neutral",
    appearance: "Cheerful, blood-flecked apron, a tray of alarming pliers, a smile with a gold tooth.",
    personality: ["Jolly", "Morbid", "Practical"],
    mannerisms: "Appraises everyone's teeth; tells gory stories to relax patients (it doesn't work).",
    voice: "Loud, friendly, far too casual about pain.",
    motivation: "To save enough to open a real surgery and stop working out of a cart.",
    secret: "She sells the gold teeth she pulls from the dead, and not all of them were dead first.",
    hook: "Offers to pull a 'troublesome' tooth nobody asked about, for a very fair price.",
  },
  {
    name: "Corvin Ashe",
    race: "Tiefling",
    occupation: "Funeral-mask carver",
    alignment: "Neutral Good",
    appearance: "Soot-dark skin, ember eyes, a satchel of pale carved masks that seem to watch you back.",
    personality: ["Solemn", "Empathetic", "Private"],
    mannerisms: "Studies faces to carve them; speaks of the dead in the present tense.",
    voice: "Hushed and grave, with unexpected warmth.",
    motivation: "To carry a finished mask to a grave he was paid to honour but never told whose it is.",
    secret: "The masks let him briefly hear the last words of whoever they're carved for — and he's addicted to it.",
    hook: "Asks the party to help him find a grave marked only by a symbol he sketches in the dirt.",
  },
  {
    name: "Goodwife Trill",
    race: "Human",
    occupation: "Egg-and-cheese seller",
    alignment: "Neutral Good",
    appearance: "Plump, rosy, a basket of speckled eggs and waxed rounds, a shawl mended a dozen times.",
    personality: ["Chatty", "Nosy", "Big-hearted"],
    mannerisms: "Knows everyone's business and shares it freely; presses food on strangers.",
    voice: "Sing-song, motherly, relentlessly cheerful.",
    motivation: "To get to market and back before her husband notices how much she's giving away.",
    secret: "She's been quietly feeding a 'beggar' in the woods who is in fact a wanted fugitive she's grown fond of.",
    hook: "Trades news for company on the road and lets slip exactly the rumour the party needs.",
  },
  {
    name: "Marshal Crane",
    race: "Human",
    occupation: "Circuit judge",
    alignment: "Lawful Neutral",
    appearance: "Severe, black-clad, a chain of office, a clerk's box of writs balanced on the saddle.",
    personality: ["Stern", "Incorruptible", "Weary"],
    mannerisms: "Weighs every word as testimony; refuses gifts of any kind.",
    voice: "Dry, exact, courtroom-cadenced.",
    motivation: "To reach the next assize town and clear a docket of cases before the harvest unrest spreads.",
    secret: "He let a guilty man hang once on bad evidence and now rules so harshly he creates new injustices.",
    hook: "Deputizes the party (whether they like it or not) to escort a prisoner to trial.",
  },
  {
    name: "Little Owl",
    race: "Human",
    occupation: "Feral orphan",
    alignment: "Chaotic Neutral",
    appearance: "A ragged child of indeterminate age, too quiet, too quick, eyes that miss nothing.",
    personality: ["Wary", "Feral", "Fiercely loyal once won"],
    mannerisms: "Hoards food in pockets; vanishes when voices rise; never says please.",
    voice: "Rare and rusty, words half-remembered.",
    motivation: "To survive the road and keep the younger ones she hides from the slavers fed.",
    secret: "She's been leading travellers into an ambush to buy the slavers' silence — and hates herself for it.",
    hook: "Tugs a sleeve, points down a side trail, says only 'this way' — and means more than one thing by it.",
  },
  {
    name: "Bram Tolliver",
    race: "Human",
    occupation: "Ferryman",
    alignment: "True Neutral",
    appearance: "Knotted with muscle, river-damp, a pole worn smooth, a coin always tucked behind his ear.",
    personality: ["Laconic", "Superstitious", "Fair"],
    mannerisms: "Won't cross at dusk; flips a coin to decide anything he doesn't care about.",
    voice: "Slow, river-smoothed, fond of weather-talk.",
    motivation: "To keep the crossing running and never, ever cross after dark again.",
    secret: "Something in the river takes a passenger each year, and Bram chooses who by who tips worst.",
    hook: "Names a fair fare to cross — and a strange condition: all aboard before the sun touches the water.",
  },
  {
    name: "Vex Underholt",
    race: "Drow",
    occupation: "Surface exile",
    alignment: "Chaotic Good",
    appearance: "Cloaked against the light, ash-grey skin, hands raw from work she was never raised to do.",
    personality: ["Guarded", "Dry-witted", "Proud"],
    mannerisms: "Squints in daylight; tests food for poison out of pure habit.",
    voice: "Low, accented, with a blade's edge of sarcasm.",
    motivation: "To prove a surface life is possible before the cold or the prejudice kills her first.",
    secret: "Her house didn't exile her — she fled after warning a surface town of a raid, and they'd kill her for the warning.",
    hook: "Trades hard-won survival lore for a night's safe watch, expecting to be turned away.",
  },
  {
    name: "Father Greaves",
    race: "Human",
    occupation: "Travelling confessor",
    alignment: "Lawful Good",
    appearance: "Stout, kind-faced, a portable shrine on his back, knees gone from a lifetime of kneeling.",
    personality: ["Forgiving", "Tireless", "Perceptive"],
    mannerisms: "Hears confession from anyone, including bandits; never repeats a word of it.",
    voice: "Round, gentle, endlessly reassuring.",
    motivation: "To reach a condemned man's cell and offer last rites before the rope.",
    secret: "A confession he heard names the real killer — and the seal of his office forbids him to ever tell.",
    hook: "Asks for swift company to the gaol-town, growing more troubled the closer they get.",
  },
  {
    name: "Thessaly Dunn",
    race: "Human",
    occupation: "Cartographer",
    alignment: "Neutral Good",
    appearance: "Sun-squinting, satchel of rolled maps, a spyglass, boots resoled more than once.",
    personality: ["Curious", "Precise", "Adventurous"],
    mannerisms: "Sketches everything; argues with her own old maps; names hills she passes.",
    voice: "Quick, enthusiastic, prone to direction-giving nobody asked for.",
    motivation: "To map the one valley every existing chart leaves suspiciously blank.",
    secret: "The valley is blank on purpose — the last cartographer who filled it in disappeared, and she has his notes.",
    hook: "Hires guides into the unmapped valley, downplaying just how many others didn't come back.",
  },
  {
    name: "Mungo Baskin",
    race: "Halfling",
    occupation: "Travelling brewer",
    alignment: "Chaotic Good",
    appearance: "Barrel-shaped, foam in his whiskers, a cart of clinking kegs and a tasting-cup on a string.",
    personality: ["Boisterous", "Generous", "Loyal"],
    mannerisms: "Toasts everything; judges people by how they hold a cup; sings when drunk (often).",
    voice: "Booming, hearty, sloppier as the day goes on.",
    motivation: "To deliver a wedding ale to a village three days off before it sours.",
    secret: "A keg in the cart isn't ale — it's a dwarf's ashes he's smuggling home, disguised among the barrels.",
    hook: "Shares a free cup, then sheepishly asks for muscle to guard the cart the rest of the way.",
  },
  {
    name: "The Veiled Lady",
    race: "Unknown",
    occupation: "Toll-keeper of a bridge that shouldn't exist",
    alignment: "Lawful Neutral",
    appearance: "A still figure in grey veils at a bridge no map shows, voice the only proof there's a person beneath.",
    personality: ["Implacable", "Courteous", "Ancient"],
    mannerisms: "Asks each traveller the same three questions; never repeats herself; never blinks (if she blinks).",
    voice: "Soft, formal, seeming to come from just behind you.",
    motivation: "To collect the toll the old pact demands and let no one cross who cannot pay it.",
    secret: "The toll is never coin — it's a memory, taken on crossing, and she is made entirely of the ones she's kept.",
    hook: "Bars a shortcut over her bridge until each traveller answers truly what they'd give to cross.",
  },

  // ── Expansion batch ──────────────────────────────────────────────────────────
  // Broadens the pool past the original 36 for cross-campaign variety, leaning
  // into races the first set under-used (it was Human-heavy) and spreading
  // occupation / alignment / disposition. Same discipline: a twist in the secret,
  // an actionable hook. Names deduped against everything above.
  {
    name: "Yorvath Emberscale",
    race: "Dragonborn",
    occupation: "Caravan master",
    alignment: "Lawful Neutral",
    appearance: "Bronze-scaled, broad as a doorway, a merchant's chain of office over a soldier's old burns down one arm.",
    personality: ["Commanding", "Fair", "Tradition-bound"],
    mannerisms: "Seals every deal with a shared cup; recites his caravan's roster from memory each dawn.",
    voice: "Deep and formal, with a faint smoke-rasp.",
    motivation: "To bring his caravan over the pass intact one last time before he hands it to his daughter.",
    secret: "His daughter died on the last crossing; he keeps her name on the roster and pretends she rides ahead.",
    hook: "Hires extra blades for the pass and pays well — provided no one asks about the empty wagon at the front.",
  },
  {
    name: "Halcyon",
    race: "Aasimar",
    occupation: "Itinerant healer",
    alignment: "Neutral Good",
    appearance: "Faintly luminous skin gone ashen, feathered scars across her back where wings once were, a worn healer's kit.",
    personality: ["Serene", "Doubting", "Selfless"],
    mannerisms: "Hums a celestial hymn while she works; won't take payment, only a meal.",
    voice: "Warm and clear, with an odd resonance like two voices almost in unison.",
    motivation: "To heal enough good into the world to be called home again.",
    secret: "The voice that guided her has gone silent, and she fears her exile is permanent — or deserved.",
    hook: "Tends a sick traveller for free, then asks, almost shyly, whether the party has heard any voice from above lately.",
  },
  {
    name: "Old Shellback",
    race: "Tortle",
    occupation: "Wandering hermit",
    alignment: "Lawful Good",
    appearance: "Ancient, moss on his shell, a walking staff and a pack holding nothing but tea and a single book.",
    personality: ["Tranquil", "Wry", "Patient"],
    mannerisms: "Answers haste with a longer pause; brews tea before any serious talk.",
    voice: "Slow and dry, a chuckle always near the surface.",
    motivation: "To walk the whole coast road once more before he sets down his shell for good.",
    secret: "He was a feared war-leader a lifetime ago; he walks to apologize, town by town, to people long dead.",
    hook: "Shares tea and a story, and mentions — only if asked twice — the ruin ahead he's deliberately avoiding.",
  },
  {
    name: "Cinder Vael",
    race: "Fire Genasi",
    occupation: "Travelling farrier",
    alignment: "Chaotic Good",
    appearance: "Skin like banked coals, hair that smokes when she's angry, a portable forge slung on a patient mule.",
    personality: ["Hot-tempered", "Generous", "Honest"],
    mannerisms: "Lights her pipe off her own thumb; bangs metal while she thinks.",
    voice: "Brassy and loud, quick to laugh and quicker to swear.",
    motivation: "To find the smith who taught her and tell him the forge he left her is still lit.",
    secret: "She burned down a cruel noble's stable — and the master in it — and has been moving ever since.",
    hook: "Offers to re-shoe the party's horses cheap, then asks, casual, whether the road behind has any riders on it.",
  },
  {
    name: "Tik",
    race: "Goblin",
    occupation: "Reformed trapsmith",
    alignment: "Neutral Good",
    appearance: "Small and twitchy, one ear notched, a bandolier of disarmed trap parts worn like trophies.",
    personality: ["Anxious", "Clever", "Eager to prove himself"],
    mannerisms: "Flinches first, helps second; names every trap he's ever built.",
    voice: "High, fast, apologetic.",
    motivation: "To undo the traps his old warband left on the roads before some child finds one.",
    secret: "One trap he can't locate killed a family, and he's been searching for it for years.",
    hook: "Warns the party off a 'safe' stretch of road and begs to come along to disarm what's waiting there.",
  },
  {
    name: "Sniv Coppertooth",
    race: "Kobold",
    occupation: "Self-appointed dragon's envoy",
    alignment: "Lawful Neutral",
    appearance: "Rust-red scales, an oversized tabard bearing a wyrm's sigil, a ledger of 'tributes' clutched tight.",
    personality: ["Pompous", "Devoted", "Surprisingly brave"],
    mannerisms: "Announces his master's full titles before speaking; bows to no one but dragons.",
    voice: "Reedy and grandiose, cracking when frightened.",
    motivation: "To collect tribute along the road and win back his exiled dragon-lord's favour.",
    secret: "His dragon-lord is long dead; Sniv guards an empty lair and can't bear to admit it's just him now.",
    hook: "Demands tribute for safe passage, then negotiates down to almost nothing if treated with any respect.",
  },
  {
    name: "Sessth",
    race: "Lizardfolk",
    occupation: "Marsh guide",
    alignment: "True Neutral",
    appearance: "Mottled green-grey and unblinking, a necklace of teeth and river-stones, a spear worn smooth.",
    personality: ["Literal", "Calm", "Pragmatic"],
    mannerisms: "States facts without softening them; eats while others talk.",
    voice: "Flat, sibilant, economical.",
    motivation: "To trade safe passage through the marsh for the metal tools its clan cannot forge.",
    secret: "It's leading fewer travellers out than in lately — the marsh has begun taking them — and it's deciding whether to care.",
    hook: "Offers to guide the party through the bog for a fair price in steel, and means exactly that — no more.",
  },
  {
    name: "Tarrow Deepcurrent",
    race: "Triton",
    occupation: "Landlocked sailor",
    alignment: "Chaotic Good",
    appearance: "Sea-blue skin gone dull and dry, a sailor's coat far from any sea, eyes forever seeking water.",
    personality: ["Restless", "Loyal", "Homesick"],
    mannerisms: "Reads the weather obsessively; keeps a vial of seawater he refuses to open.",
    voice: "Rolling and musical, salt still in it.",
    motivation: "To reach the coast and answer a call from the deep he's felt since the day he wandered inland.",
    secret: "He came ashore to flee something rising in his home waters — and the call may be it, hunting.",
    hook: "Asks the fastest road to the sea and will guard the party's back the whole way for the company.",
  },
  {
    name: "Quoth",
    race: "Kenku",
    occupation: "Message-thief turned courier",
    alignment: "Chaotic Neutral",
    appearance: "Ragged black feathers, head cocked, a satchel of letters not all of which are his to carry.",
    personality: ["Sly", "Lonely", "Mimic"],
    mannerisms: "Speaks in stolen voices; repeats the last thing you said when nervous.",
    voice: "A patchwork of other people's words and tones.",
    motivation: "To find his own voice by collecting enough others — and to be, just once, believed.",
    secret: "He's been reading and reselling the letters he carries; one he sold started a feud that's killing people.",
    hook: "Offers to carry a message faster than any horse, in a voice unsettlingly like someone you trust.",
  },
  {
    name: "Mirri Ninetongue",
    race: "Tabaxi",
    occupation: "Curio peddler",
    alignment: "Chaotic Good",
    appearance: "Sleek spotted fur, a coat sewn with a hundred pockets, eyes that catch every glint.",
    personality: ["Curious", "Acquisitive", "Charming"],
    mannerisms: "Touches everything; trades stories for trinkets; her tail betrays her mood.",
    voice: "Purring, quick, delighted.",
    motivation: "To find the one object her grandmother described in a deathbed story and never named.",
    secret: "She lifts one small thing from everyone she meets — not for its value, for the story it carries.",
    hook: "Offers a strange trinket in trade and lets slip she 'collected' something useful from a traveller down the road.",
  },
  {
    name: "Ondu the Elder",
    race: "Loxodon",
    occupation: "Memory-keeper",
    alignment: "Lawful Good",
    appearance: "Grey-hided and slow, vast ears, a staff hung with knotted cords recording what he's sworn to remember.",
    personality: ["Solemn", "Kind", "Unhurried"],
    mannerisms: "Ties a knot for every promise; never forgets a face or a slight.",
    voice: "Deep and rumbling, like distant thunder.",
    motivation: "To carry the remembered history of a fallen village to anyone who will keep it.",
    secret: "He survived because he ran; the knots are penance, and one cord he never shows anyone is his own shame.",
    hook: "Asks the party to hear and carry one story onward, so it isn't lost when he finally is.",
  },
  {
    name: "Whitemane Tau",
    race: "Centaur",
    occupation: "Plains outrider",
    alignment: "Neutral Good",
    appearance: "Dun coat, greying mane, a hunter's bow and a herd-brand long faded, scars of many ranges.",
    personality: ["Proud", "Watchful", "Generous to guests"],
    mannerisms: "Refuses to be approached from behind; tests strangers with a long silent stare.",
    voice: "Strong and plain, with a herder's carrying call.",
    motivation: "To find new grazing for a herd that's no longer there to graze.",
    secret: "Raiders took his herd and family; he rides the old ranges still pretending to scout for them.",
    hook: "Warns the party off raider land ahead, then offers to ride with them if they're fool enough to go.",
  },
  {
    name: "Pellam Hoof",
    race: "Satyr",
    occupation: "Debt-running reveler",
    alignment: "Chaotic Neutral",
    appearance: "Curling horns, a wine-stained vest, pipes at his hip, a grin that owes money in three towns.",
    personality: ["Hedonistic", "Quick-witted", "Cowardly until cornered"],
    mannerisms: "Turns any moment into a party; deflects trouble with a song.",
    voice: "Lilting and teasing, irresistibly merry.",
    motivation: "To outrun his creditors long enough to throw one last, glorious, ruinous festival.",
    secret: "His 'debts' are bargains with a fey lord, and the festival is the only thing keeping the price unpaid.",
    hook: "Invites the party to a revel up the road that he very much needs witnesses — or a buffer — for.",
  },
  {
    name: "Issytha",
    race: "Yuan-ti pureblood",
    occupation: "Silk merchant",
    alignment: "Lawful Evil",
    appearance: "Coldly beautiful, faintly scaled at the wrists, a caravan of fine silks and colder eyes.",
    personality: ["Poised", "Patient", "Manipulative"],
    mannerisms: "Never raises her voice; remembers every favour owed to the decimal.",
    voice: "Smooth and cool, hypnotically even.",
    motivation: "To open a trade route that quietly seeds her cult's influence in three new cities.",
    secret: "The silk is a front; the real cargo is people, vanished from the road and bound for the temple.",
    hook: "Offers the party lucrative escort work — and a discount that should make them suspicious and won't.",
  },
  {
    name: "Bramble",
    race: "Shifter",
    occupation: "Moon-touched tracker",
    alignment: "Neutral",
    appearance: "Lean and beast-eyed, fur rising along the arms at dusk, a tracker's quiet economy of movement.",
    personality: ["Instinctive", "Loyal", "Tormented"],
    mannerisms: "Sniffs the air before answering; goes still and strange as the moon rises.",
    voice: "Low and clipped, half a growl on full-moon nights.",
    motivation: "To reach the deep wood before the moon turns, where she can run without endangering anyone.",
    secret: "On the worst nights she isn't sure what she's done until she wakes — and she's started waking with blood.",
    hook: "Offers to track anything for the party, but insists they leave her behind, alone, by nightfall.",
  },
  {
    name: "Captain Drazhk",
    race: "Hobgoblin",
    occupation: "Free-company captain",
    alignment: "Lawful Neutral",
    appearance: "Disciplined and scarred, banded armour kept spotless, a furled company standard on his back.",
    personality: ["Honourable", "Strict", "Pragmatic"],
    mannerisms: "Honours every contract to the letter; salutes a worthy foe.",
    voice: "Crisp and commanding, no wasted words.",
    motivation: "To win his company an honest name in lands that see only the monster in his face.",
    secret: "His last contract was to crush a peasant revolt; he let half escape and reported them dead.",
    hook: "Offers the party a fair contract — and a very sharp eye if they try to break it.",
  },
  {
    name: "Murreth Ironvow",
    race: "Orc",
    occupation: "Wandering war-shaman",
    alignment: "Neutral Good",
    appearance: "Grey-green and tusked, ritual scars and ancestral fetishes, a drum worn at the hip.",
    personality: ["Solemn", "Wise", "Burdened"],
    mannerisms: "Drums softly to think; speaks the names of his dead before sleep.",
    voice: "Deep and rhythmic, careful in the common tongue.",
    motivation: "To carry the spirits of a fallen clan to a sacred peak so they can finally rest.",
    secret: "He led the raid that doomed the clan; the spirits he carries blame him, and he agrees with them.",
    hook: "Asks safe passage to the mountains and offers true healing — and unsettling honesty — in return.",
  },
  {
    name: "Doc Mercer",
    race: "Human",
    occupation: "Snake-oil seller",
    alignment: "Chaotic Neutral",
    appearance: "A loud checked coat, a wagon painted with miracles, a smile selling something the whole time.",
    personality: ["Glib", "Adaptable", "Secretly soft"],
    mannerisms: "Has a tonic for everything; never lets a silence go unsold.",
    voice: "Honeyed and rapid, a carnival barker's roll.",
    motivation: "To clear the region ahead of the last three towns that want their money back.",
    secret: "One of his 'fake' tonics actually works — made by accident, unrepeatable — and dangerous people know it.",
    hook: "Sells the party a useless remedy, then begs protection when men come asking after a very real cure.",
  },
  {
    name: "Sera Ratcatcher",
    race: "Human",
    occupation: "Rat-catcher",
    alignment: "Neutral Good",
    appearance: "Wiry and sharp-nosed, a pack of clever terriers, a belt of cages, never quite clean.",
    personality: ["Practical", "Kind", "Unflinching"],
    mannerisms: "Talks to her dogs more than to people; reads a town's health by its vermin.",
    voice: "Brisk and low, fond only when speaking to the dogs.",
    motivation: "To reach the next town before the plague the rats are fleeing reaches it first.",
    secret: "She knows the sickness is coming and that no one heeds a rat-catcher until it's too late.",
    hook: "Warns the party the rats are running the wrong way — toward them, away from something worse.",
  },
  {
    name: "Bull Hask",
    race: "Human",
    occupation: "Retired pit fighter",
    alignment: "Lawful Neutral",
    appearance: "A wall of old muscle and older scars, cauliflower ears, hands that can't quite open all the way.",
    personality: ["Gentle", "Tired", "Protective"],
    mannerisms: "Cracks his knuckles slowly; steps between trouble and the weak without thinking.",
    voice: "Soft and slow, more thoughtful than his size suggests.",
    motivation: "To reach a quiet farm and never throw another punch as long as he lives.",
    secret: "The men who hold his old fighting debt are tracking him to drag him back for one last bout.",
    hook: "Asks the road to a far village and quietly hopes the party are going the same way — and hard to scare.",
  },
  {
    name: "Madame Estraine",
    race: "Human",
    occupation: "Fortune-teller",
    alignment: "Neutral",
    appearance: "Layered shawls, ringed fingers, a wagon of beads, a real chill that follows her predictions.",
    personality: ["Theatrical", "Weary", "Honest under the act"],
    mannerisms: "Hams up every reading; goes very quiet when a true vision comes.",
    voice: "Husky and dramatic, dropping flat when she means it.",
    motivation: "To find the one person her cards keep showing — a death she might still be able to prevent.",
    secret: "Most readings are showmanship, but the true ones always come to pass, and she can't stop them.",
    hook: "Reads the party's fortune for coin, then refuses payment and warns one of them, white-faced, to turn back.",
  },
  {
    name: "Coll Ashfoot",
    race: "Human",
    occupation: "Charcoal burner",
    alignment: "True Neutral",
    appearance: "Soot-black to the bone, slow and solitary, a smouldering mound always tended behind him.",
    personality: ["Reclusive", "Steady", "Superstitious"],
    mannerisms: "Never lets his fire fully out; leaves an offering at the woodline each night.",
    voice: "Rough and quiet, rarely used.",
    motivation: "To work his lonely trade in the deep wood and be left entirely alone.",
    secret: "The nightly offering keeps something in the trees fed and friendly; lately it wants more than bread.",
    hook: "Reluctantly warns the party not to camp in the woods, and won't say why past a certain treeline.",
  },
  {
    name: "Polly Drover",
    race: "Halfling",
    occupation: "Cattle drover",
    alignment: "Neutral Good",
    appearance: "Bow-legged and dust-caked, a drover's whip and a battered hat, a herd that dwarfs her.",
    personality: ["Tough", "Cheerful", "Stubborn"],
    mannerisms: "Whistles signals to the herd; names every cow; sleeps in the saddle.",
    voice: "Loud and twangy, carries across a field.",
    motivation: "To get her herd to market through a stretch of road that's been eating livestock.",
    secret: "She's glimpsed what's taking the cattle, and it walks upright — but she's telling herself it was a bear.",
    hook: "Asks the party to ride drag through the bad stretch, splitting the profit if they all make it.",
  },
  {
    name: "Wendel Quib",
    race: "Dwarf",
    occupation: "Failed wizard's apprentice",
    alignment: "Chaotic Good",
    appearance: "Singed beard, robes full of burn-holes, a wand he doesn't trust and a book he can barely read.",
    personality: ["Earnest", "Accident-prone", "Determined"],
    mannerisms: "Mutters incantations slightly wrong; ducks reflexively after every spell.",
    voice: "Nervous and fast, trailing into 'oh no'.",
    motivation: "To master the spell that got him expelled and prove the master who failed him wrong.",
    secret: "The spell isn't failing — it's working, slowly summoning something patient, and he hasn't noticed.",
    hook: "Begs the party to let him 'just try something' to help, which is exactly as risky as it sounds.",
  },
  {
    name: "Aelinor Vance",
    race: "Elf",
    occupation: "Travelling exorcist",
    alignment: "Lawful Good",
    appearance: "Pale and severe, ritual chalk and silver bells, eyes that look slightly past you at things behind.",
    personality: ["Grave", "Compassionate", "Exhausted"],
    mannerisms: "Salts thresholds; addresses the empty air politely; never sleeps in one place twice.",
    voice: "Quiet and steady, with the cadence of prayer.",
    motivation: "To lay to rest a spirit that's followed her a century, by finishing what it asks.",
    secret: "The spirit is her own brother, and finishing what he asks means avenging a murder she committed.",
    hook: "Warns the party a place ahead is haunted and asks their help to enter it — for the spirit's sake, she says.",
  },
  {
    name: "Fizwick Cogsworth",
    race: "Gnome",
    occupation: "Golem-keeper",
    alignment: "Neutral",
    appearance: "Tiny and oil-stained, leading a massive half-broken clay golem on a chain it could snap any time.",
    personality: ["Doting", "Defensive", "Lonely"],
    mannerisms: "Talks to the golem like a child; repairs it mid-conversation; bristles at the word 'thing'.",
    voice: "Clipped and proud, soft only when addressing the golem.",
    motivation: "To find the rare clay that will let him wake the golem fully — as a mind, not a tool.",
    secret: "It's already awake, and has been for years; it stays a 'tool' because it doesn't want to break his heart.",
    hook: "Hires muscle to guard him to a distant clay-pit, the golem watching the party with eyes that clearly think.",
  },
  {
    name: "Marrow",
    race: "Tiefling",
    occupation: "Debt collector",
    alignment: "Lawful Neutral",
    appearance: "Tall and immaculate, ledger and lockbox, horns lacquered black, a smile filed as sharp as his terms.",
    personality: ["Polite", "Relentless", "Precise"],
    mannerisms: "Quotes interest rates like poetry; never threatens, only itemizes.",
    voice: "Cool and courteous, terrible in its calm.",
    motivation: "To collect a long-overdue debt in the next town, with full and lawful interest.",
    secret: "The debtor is his estranged father, and Marrow can't decide whether he wants payment or an apology.",
    hook: "Asks if the party know the road to the next town — and whether a certain name means anything to them.",
  },
  {
    name: "Honeythief Gull",
    race: "Half-orc",
    occupation: "Travelling beekeeper",
    alignment: "Neutral Good",
    appearance: "Massive and gentle-handed, a veil and a cart of humming hives, stung so often he no longer swells.",
    personality: ["Placid", "Patient", "Quietly sad"],
    mannerisms: "Moves slowly so as not to alarm the bees; tastes the honey of every region.",
    voice: "Low and calm, with long companionable silences.",
    motivation: "To find a meadow of a flower his late wife loved and make the honey she never got to taste.",
    secret: "His bees are subtly fey-touched, and their honey shows the eater a glimpse of what they most regret.",
    hook: "Offers the party honey that tastes of memory, then asks if they've seen a particular pale blue flower.",
  },
  {
    name: "Widow Carran",
    race: "Human",
    occupation: "Battlefield scavenger",
    alignment: "Neutral",
    appearance: "Black-clad and hard-eyed, a cart of salvaged armour and a wedding ring she still wears.",
    personality: ["Bitter", "Resourceful", "Fair"],
    mannerisms: "Prices the dead's gear without flinching; says a quiet word over each piece before selling it.",
    voice: "Flat and dry, grief sanded down to function.",
    motivation: "To earn enough off the war's leavings to buy back the farm the war took.",
    secret: "She searches every field for her husband's body to bury him, and sells the rest to fund the looking.",
    hook: "Trades cheap, serviceable gear and asks the party to watch for a shield with a green hawk on it.",
  },
  {
    name: "Lamplighter Sole",
    race: "Human",
    occupation: "Keeper of a dead town's lamps",
    alignment: "Lawful Neutral",
    appearance: "Stooped and careful, a long lamp-pole and a ring of keys, lighting streets no one walks.",
    personality: ["Dutiful", "Lonely", "Gently unwell"],
    mannerisms: "Greets people who aren't there by name; lights every lamp at dusk without fail.",
    voice: "Soft and courteous, addressing a town that's gone.",
    motivation: "To keep the lamps lit so the townsfolk can find their way home when they return.",
    secret: "The town didn't empty — it was taken, all at once, and Sole hid; the lamps are guilt, not hope.",
    hook: "Welcomes the party to a town of empty houses and lit lamps, and begs them to stay 'until the others get back'.",
  },
  {
    name: "Briar Dowse",
    race: "Half-elf",
    occupation: "Water-witch and dowser",
    alignment: "Chaotic Good",
    appearance: "Sun-freckled and barefoot, a forked hazel rod and a string of river-charms, always a little damp.",
    personality: ["Free-spirited", "Intuitive", "Evasive"],
    mannerisms: "Follows her rod mid-sentence; won't drink standing water; hums to wells.",
    voice: "Lilting and drifting, hard to pin down.",
    motivation: "To find the source of a poisoned river before it reaches the valley downstream.",
    secret: "The poison is her doing — a working gone wrong — and she's racing her own mistake to undo it first.",
    hook: "Begs the party upriver with her, urgently, refusing to say what they're racing until they're committed.",
  },
  {
    name: "Grin Mallock",
    race: "Human",
    occupation: "Escaped convict",
    alignment: "Chaotic Neutral",
    appearance: "Shorn head, a chafed wrist where an iron used to be, prison-pale, eyes always on the road behind.",
    personality: ["Jumpy", "Wily", "Decent at heart"],
    mannerisms: "Sits facing the exit; tests every name he gives; can't stop rubbing his wrist.",
    voice: "Low and fast, dropping to nothing near strangers.",
    motivation: "To reach the border and the brother who can swear he was jailed for another man's crime.",
    secret: "He did do it — but the man he killed was the one who sold his sister, and he'd do it again.",
    hook: "Asks the quietest road to the border and offers honest coin to anyone who won't ask his name twice.",
  },
  {
    name: "Goodman Teal",
    race: "Human",
    occupation: "Leech-gatherer and bleeder",
    alignment: "Neutral",
    appearance: "Pallid and wet-sleeved, a jar of writhing leeches and a barber's blades, a careful bedside calm.",
    personality: ["Soft-spoken", "Morbid", "Genuinely caring"],
    mannerisms: "Names his leeches; checks your colour unprompted; far gentler than his trade looks.",
    voice: "Hushed and soothing, like a man used to calming the dying.",
    motivation: "To reach a fevered village and try a treatment the learned physicians laughed him out of.",
    secret: "His method actually works — he stumbled on real medicine — and a guild wants him silenced for it.",
    hook: "Offers to treat any ailment the party carries, and asks escort past the men 'in physicians' robes' ahead.",
  },
  {
    name: "Yarrow Penn",
    race: "Human",
    occupation: "Travelling schoolteacher",
    alignment: "Lawful Good",
    appearance: "Threadbare respectable, a slate and chalk, a satchel of dog-eared primers, ink on every finger.",
    personality: ["Patient", "Idealistic", "Brave in small ways"],
    mannerisms: "Explains everything twice; can't pass a child without teaching them something.",
    voice: "Clear and kindly, with a lecturer's habit of pausing for answers.",
    motivation: "To reach a remote village that's never had a teacher and start its first school.",
    secret: "He's fleeing a city that burned books — and his own — and the school is defiance dressed as charity.",
    hook: "Asks the road to a far hamlet and, learning the party's trades, can't help asking them to teach a lesson.",
  },
  {
    name: "Roan Tessik",
    race: "Human",
    occupation: "Horse trader",
    alignment: "Chaotic Good",
    appearance: "Bandy-legged and weather-cracked, a string of fine horses, and a patter you shouldn't quite trust.",
    personality: ["Charming", "Sharp", "Sentimental about horses"],
    mannerisms: "Talks up every nag as a champion; treats the horses better than the customers.",
    voice: "Fast and friendly, with a closer's warmth.",
    motivation: "To sell off his string and retire — except he loves them too much to part with the best.",
    secret: "His prize stallion is a polymorphed nobleman he hasn't worked out how to change back, or whether to.",
    hook: "Offers the party a suspiciously good deal on a horse with very intelligent, very pleading eyes.",
  },
  {
    name: "Sashka Roe",
    race: "Human",
    occupation: "Travelling actor",
    alignment: "Chaotic Good",
    appearance: "Greasepaint half-scrubbed, a cart of costumes and a folding stage, a different accent every hour.",
    personality: ["Flamboyant", "Observant", "Insecure"],
    mannerisms: "Slips into characters mid-talk; reads a crowd before it forms; fishes for applause.",
    voice: "Mercurial — whatever the scene demands.",
    motivation: "To stage one true performance that makes an audience feel something real, not just laugh.",
    secret: "Her troupe's 'plays' cover smuggling people out of a tyrant's reach, hidden in the costume cart.",
    hook: "Invites the party to tonight's show up the road and quietly asks if any of them can act under pressure.",
  },
  {
    name: "Knacker Bain",
    race: "Human",
    occupation: "Knacker and renderer",
    alignment: "True Neutral",
    appearance: "Aproned in stains best not named, a cart of bones and hides, a cleaver and a grim efficiency.",
    personality: ["Blunt", "Unbothered", "Oddly philosophical"],
    mannerisms: "Talks about death like weather; sharpens his blade while chatting.",
    voice: "Gruff and matter-of-fact, occasionally surprisingly deep.",
    motivation: "To collect a dead beast from the road ahead the locals are paying well to be rid of.",
    secret: "What he's been rendering lately isn't always beast, and he's stopped asking the buyers questions.",
    hook: "Mentions a fat bounty on a carcass up the road and offers to split it if the party do the killing.",
  },
  {
    name: "Ysolde Kerr",
    race: "Human",
    occupation: "War profiteer and sutler",
    alignment: "Lawful Evil",
    appearance: "Well-fed where others starve, a wagon of overpriced necessities, a smile and an abacus.",
    personality: ["Affable", "Ruthless", "Cowardly"],
    mannerisms: "Calls everyone 'friend'; raises prices as the road worsens; flinches at real danger.",
    voice: "Jovial and oily, quick to bargain.",
    motivation: "To follow the armies and sell the desperate what they need at exactly what they can't afford.",
    secret: "She's been selling the same intelligence to both sides of the war, and both have begun to suspect.",
    hook: "Offers the party 'a friend's price' on supplies, then tries to hire them as guards when a rider appears behind.",
  },
  {
    name: "Three-Coin Tam",
    race: "Human",
    occupation: "Beggar-king and road informant",
    alignment: "Chaotic Good",
    appearance: "Ragged but shrewd, a tin cup, a network of nods from every other beggar on the road.",
    personality: ["Streetwise", "Generous", "Watchful"],
    mannerisms: "Reads boots to judge a person; shares his cup's takings with the smaller beggars.",
    voice: "Wheedling in public, sharp and clear in private.",
    motivation: "To keep the road's forgotten people fed through a hard winter the lords won't notice.",
    secret: "He runs the region's best information network out of a beggar's cup, and three nobles would kill to own it.",
    hook: "Asks for a coin, then offers — quietly, for real coin — to name exactly who's been following the party.",
  },
  {
    name: "Selka Wren",
    race: "Human",
    occupation: "Falconer and messenger",
    alignment: "Neutral Good",
    appearance: "A leather gauntlet, a hooded hawk, sharp eyes shared with the bird, a satchel of message-rings.",
    personality: ["Independent", "Loyal", "Terse"],
    mannerisms: "Communicates with the hawk by whistle; trusts the bird's read of people over her own.",
    voice: "Brief and even, warmer only when addressing the hawk.",
    motivation: "To deliver a war-warning to a town before the army it concerns arrives.",
    secret: "She's already too late and knows it; she flies on so she won't have to be the one who stopped trying.",
    hook: "Lands her exhausted hawk near the party, desperate for fresh legs to carry a warning the bird can't finish.",
  },
  {
    name: "Cassius Holt",
    race: "Human",
    occupation: "Relic smuggler",
    alignment: "Chaotic Neutral",
    appearance: "Respectable traveller's clothes, a locked case never out of reach, eyes that price every exit.",
    personality: ["Smooth", "Paranoid", "Principled in his own way"],
    mannerisms: "Keeps one hand on the case; changes inns nightly; never drinks what he didn't pour.",
    voice: "Measured and quiet, a diplomat's care.",
    motivation: "To get a stolen relic to a buyer who'll keep it from a cult — not sell it back to them.",
    secret: "The relic is awake and whispering, and it's been bending his chosen route to lead him to the cult.",
    hook: "Hires the party as 'escort for a delicate antique', and grows visibly worse the longer he carries it.",
  },
  {
    name: "Grandmother Sel",
    race: "Human",
    occupation: "Travelling storyteller",
    alignment: "Lawful Good",
    appearance: "Tiny and ancient, bright-eyed, a stool and a shawl, a crowd of children wherever she stops.",
    personality: ["Warm", "Wise", "Sly"],
    mannerisms: "Answers every question with a story; the stories are always, somehow, exactly relevant.",
    voice: "Rich and unhurried, made for firelight.",
    motivation: "To tell a particular forbidden story in the one town that's outlawed it, before she dies.",
    secret: "Her 'stories' are true histories the powerful have erased, and she's the last who remembers them.",
    hook: "Tells the party a tale by the fire that maps suspiciously well onto a danger waiting up their road.",
  },
  {
    name: "Hresh",
    race: "Bugbear",
    occupation: "Woodcutter and hermit",
    alignment: "Neutral Good",
    appearance: "Looming and shaggy, an axe the size of a door, a careful slowness at odds with his fearsome look.",
    personality: ["Shy", "Kind", "Easily hurt"],
    mannerisms: "Apologizes for startling people; makes himself smaller; speaks to trees before felling them.",
    voice: "Rumbling and hesitant, gentler than expected.",
    motivation: "To live alone in the woods and never again be the monster his old warband made him.",
    secret: "His old band is hunting deserters, and they'll burn the nearest village to flush him out.",
    hook: "Warns the party — terrified of being feared — that 'bad ones' are coming up the road behind him.",
  },
  {
    name: "Saffren Dusk",
    race: "Half-elf",
    occupation: "Twilight gardener and poisoner",
    alignment: "True Neutral",
    appearance: "Elegant and gloved, a cart of rare night-blooming plants, fingertips stained a dozen colours.",
    personality: ["Refined", "Amoral", "Curious"],
    mannerisms: "Sniffs every flower; speaks of poisons and cures with the same fondness.",
    voice: "Velvet and precise, unbothered.",
    motivation: "To find a legendary bloom said to be perfect antidote and perfect poison at once.",
    secret: "She sells 'medicine' to a town and 'remedy' to its rival — the same plant, killing one, curing the other.",
    hook: "Offers the party a cure for any poison and, in the same breath, an unsettling question about their enemies.",
  },
  {
    name: "Boggart Mudd",
    race: "Grung",
    occupation: "Swamp peddler",
    alignment: "Chaotic Neutral",
    appearance: "Vivid blue-skinned and wide-mouthed, a raft-cart of bog salvage and oddities, perpetually moist.",
    personality: ["Greedy", "Excitable", "Cowardly"],
    mannerisms: "Croaks when excited; haggles ferociously; flees at the first real sign of trouble.",
    voice: "Burbling and fast, rising to a squeak.",
    motivation: "To sell his bog-finds for shiny coin and buy his way out of the marsh for good.",
    secret: "One 'find' he's selling is a cursed idol the marsh wants back, and it's been calling things to retrieve it.",
    hook: "Hawks strange swamp relics to the party, one of which is very much being hunted.",
  },
  {
    name: "Sir Aldous Pyke",
    race: "Human",
    occupation: "Delusional knight-errant",
    alignment: "Chaotic Good",
    appearance: "Rusted heirloom armour, a swaybacked horse named for a hero, a chivalry no one asked for.",
    personality: ["Earnest", "Brave", "Out of touch"],
    mannerisms: "Challenges windmills and rudeness alike; addresses commoners as lords and ladies.",
    voice: "Booming and formal, gloriously sincere.",
    motivation: "To perform a deed worthy of the order that disbanded before he could ever join it.",
    secret: "The order disbanded for atrocities; the records he treasures hide crimes he'd be horrified to learn of.",
    hook: "Insists on joining the party's 'noble quest', and is, beneath the foolishness, genuinely formidable.",
  },
  {
    name: "Nettle",
    race: "Fairy",
    occupation: "Wayward fey messenger",
    alignment: "Chaotic Good",
    appearance: "A handspan tall and moth-winged, faintly glowing, riding a very put-upon road-toad.",
    personality: ["Mischievous", "Forgetful", "Loyal"],
    mannerisms: "Forgets her errand mid-sentence; pranks then apologizes; hoards buttons and secrets.",
    voice: "Tiny and bright, far too loud for her size.",
    motivation: "To deliver a fey lord's message she's mostly forgotten, to someone whose name rhymes with something.",
    secret: "The forgotten message is a declaration of war on the mortal town ahead, and she's its only warning.",
    hook: "Buzzes the party insisting one of them is 'the one'; the message, if jogged loose, matters enormously.",
  },
  {
    name: "Hollis Vane",
    race: "Human",
    occupation: "Road-and-bridge surveyor",
    alignment: "Lawful Neutral",
    appearance: "Sober and instrument-laden, a theodolite and chains, mud to the knee, a frown of constant measurement.",
    personality: ["Methodical", "Honest", "Inflexible"],
    mannerisms: "Measures everything, conversations included; distrusts anything not built to spec.",
    voice: "Dry and exact, faintly disapproving.",
    motivation: "To condemn a failing bridge ahead before a caravan trusts its weight to it.",
    secret: "He approved that bridge years ago for a bribe; condemning it now is a confession he can't say aloud.",
    hook: "Stops the party at a bridge ahead, refuses to let them cross, and can't fully explain his certainty it'll fall.",
  },
]
